import {
  CABINET_DEFAULT_MEDIA_CABLE_CHASE_DEPTH,
  CABINET_DEFAULT_MEDIA_CABLE_CHASE_HEIGHT,
  CABINET_DEFAULT_MEDIA_CABLE_CHASE_WIDTH,
  CABINET_DEFAULT_MEDIA_TV_BLOCKING_THICKNESS,
  CABINET_DEFAULT_MEDIA_TV_MOUNT_HEIGHT,
  CABINET_DEFAULT_MEDIA_TV_OPENING_HEIGHT,
  CABINET_DEFAULT_MEDIA_TV_OPENING_WIDTH,
  CABINET_DEFAULT_MEDIA_VENT_SLOT_COUNT,
  CABINET_DEFAULT_MEDIA_VENT_SLOT_HEIGHT,
  CABINET_DEFAULT_MEDIA_VENT_SLOT_SPACING,
  CABINET_DEFAULT_MEDIA_VENT_SLOT_WIDTH,
} from "./mediaWallLayout";
import {
  CABINET_DEFAULT_LIBRARY_LADDER_RAIL_DIAMETER,
  CABINET_DEFAULT_LIBRARY_LADDER_RAIL_HEIGHT,
  CABINET_DEFAULT_LIBRARY_LADDER_RAIL_PROJECTION,
  CABINET_DEFAULT_LIBRARY_LADDER_STANDOFF_COUNT,
  CABINET_DEFAULT_LIBRARY_LADDER_STANDOFF_DIAMETER,
} from "./libraryLadderLayout";
import {
  CABINET_DEFAULT_STEMWARE_RACK_DEPTH,
  CABINET_DEFAULT_STEMWARE_RACK_LANE_COUNT,
  CABINET_DEFAULT_STEMWARE_RACK_LANE_SPACING,
  CABINET_DEFAULT_STEMWARE_RACK_MOUNT_HEIGHT,
  CABINET_DEFAULT_STEMWARE_RACK_RAIL_WIDTH,
} from "./stemwareRackLayout";
import {
  CABINET_DEFAULT_LIGHTING_CHANNEL_COUNT,
  CABINET_DEFAULT_LIGHTING_CHANNEL_DEPTH,
  CABINET_DEFAULT_LIGHTING_CHANNEL_HEIGHT,
  CABINET_DEFAULT_LIGHTING_CHANNEL_INSET_FROM_FRONT,
} from "./lightingLayout";
import {
  CABINET_DEFAULT_HAMPER_BASKET_COUNT,
  CABINET_DEFAULT_HAMPER_BASKET_DEPTH,
  CABINET_DEFAULT_HAMPER_BASKET_HEIGHT,
  CABINET_DEFAULT_HAMPER_SLIDE_CLEARANCE,
} from "./hamperPullOutLayout";
import {
  CABINET_DEFAULT_SHELF_PIN_HOLE_COUNT,
  CABINET_DEFAULT_SHELF_PIN_HOLE_SPACING,
  CABINET_DEFAULT_SHELF_PIN_INSET_FROM_FRONT,
  CABINET_DEFAULT_SHELF_PIN_ROW_PAIR_COUNT,
  CABINET_DEFAULT_SHELF_PIN_START_HEIGHT,
} from "./shelfPinLayout";
import {
  CABINET_DEFAULT_DOOR_HINGE_COUNT_PER_DOOR,
  CABINET_DEFAULT_DOOR_HINGE_INSET_FROM_TOP_BOTTOM,
} from "./doorHingeLayout";
import {
  CABINET_DEFAULT_DRAWER_SLIDE_CLEARANCE,
  CABINET_DEFAULT_DRAWER_SLIDE_LENGTH,
} from "./drawerSlideLayout";
import {
  CABINET_DEFAULT_DRAWER_BOX_BACK_CLEARANCE,
  CABINET_DEFAULT_DRAWER_BOX_BOTTOM_THICKNESS,
  CABINET_DEFAULT_DRAWER_BOX_HEIGHT_CLEARANCE,
  CABINET_DEFAULT_DRAWER_BOX_SIDE_THICKNESS,
} from "./drawerBoxLayout";
import {
  CABINET_DEFAULT_INSTALLATION_CLEAT_HEIGHT,
  CABINET_DEFAULT_INSTALLATION_CLEAT_INSET_FROM_TOP,
  CABINET_DEFAULT_INSTALLATION_CLEAT_THICKNESS,
} from "./installationCleatLayout";
import {
  CABINET_DEFAULT_ANTI_TIP_ANCHOR_COUNT,
  CABINET_DEFAULT_ANTI_TIP_ANCHOR_INSET_FROM_SIDES,
} from "./antiTipAnchorLayout";
import type {
  CabinetDefinition,
  CabinetModuleDefinition,
  CabinetUnitType,
} from "./types";

export type CabinetPresetId =
  | "base"
  | "wall"
  | "tall"
  | "wardrobe"
  | "vanity"
  | "tv_console"
  | "cabinet_run"
  | "closet_system"
  | "media_wall"
  | "mudroom_storage"
  | "laundry_room"
  | "home_office_built_in"
  | "library_wall"
  | "window_seat"
  | "banquette"
  | "murphy_bed"
  | "fold_down_desk"
  | "platform_storage_bed"
  | "under_stair_storage"
  | "room_divider_storage"
  | "home_bar"
  | "kitchen_island"
  | "pantry_system"
  | "wine_storage"
  | "pet_built_in"
  | "kids_storage"
  | "hobby_storage"
  | "wall_paneling"
  | "slat_wall"
  | "ceiling_beams"
  | "coffered_ceiling"
  | "fireplace_surround"
  | "trim_package";

export const names: Record<CabinetPresetId, string> = {
  base: "Base cabinet",
  wall: "Wall cabinet",
  tall: "Tall cabinet",
  wardrobe: "Wardrobe",
  vanity: "Vanity cabinet",
  tv_console: "TV console",
  cabinet_run: "Cabinet run",
  closet_system: "Closet system",
  media_wall: "Media wall",
  mudroom_storage: "Mudroom storage",
  laundry_room: "Laundry room",
  home_office_built_in: "Home office",
  library_wall: "Library wall",
  window_seat: "Window seat",
  banquette: "Banquette",
  murphy_bed: "Murphy bed",
  fold_down_desk: "Fold-down desk",
  platform_storage_bed: "Platform storage bed",
  under_stair_storage: "Under-stair storage",
  room_divider_storage: "Room divider storage",
  home_bar: "Home bar",
  kitchen_island: "Kitchen island",
  pantry_system: "Pantry system",
  wine_storage: "Wine storage",
  pet_built_in: "Pet built-in",
  kids_storage: "Kids storage",
  hobby_storage: "Hobby storage",
  wall_paneling: "Wall paneling",
  slat_wall: "Slat wall",
  ceiling_beams: "Ceiling beams",
  coffered_ceiling: "Coffered ceiling",
  fireplace_surround: "Fireplace surround",
  trim_package: "Trim package",
};

export const unitTypeByPreset: Record<CabinetPresetId, CabinetUnitType> = {
  base: "base",
  wall: "wall",
  tall: "tall",
  wardrobe: "wardrobe",
  vanity: "vanity",
  tv_console: "tv_console",
  cabinet_run: "base",
  closet_system: "wardrobe",
  media_wall: "tall",
  mudroom_storage: "tall",
  laundry_room: "base",
  home_office_built_in: "base",
  library_wall: "wall",
  window_seat: "base",
  banquette: "base",
  murphy_bed: "wardrobe",
  fold_down_desk: "wall",
  platform_storage_bed: "base",
  under_stair_storage: "tall",
  room_divider_storage: "wall",
  home_bar: "base",
  kitchen_island: "base",
  pantry_system: "tall",
  wine_storage: "tall",
  pet_built_in: "base",
  kids_storage: "base",
  hobby_storage: "tall",
  wall_paneling: "wall",
  slat_wall: "wall",
  ceiling_beams: "wall",
  coffered_ceiling: "wall",
  fireplace_surround: "wall",
  trim_package: "wall",
};

type CabinetPresetModule = Omit<CabinetModuleDefinition, "id" | "type" | "height" | "depth"> &
  Partial<Pick<CabinetModuleDefinition, "type" | "height" | "depth">>;

export const DEFAULT_PRESET_TOE_KICK_HEIGHT_MM = 0;

export const presets: Record<
  CabinetPresetId,
  Omit<CabinetDefinition, "id" | "createdAt" | "updatedAt" | "modules" | "materials" | "hardware"> & {
    modules: CabinetPresetModule[];
  }
> = {
  base: {
    name: names.base,
    version: 1,
    units: "mm",
    totalWidth: 900,
    height: 720,
    depth: 580,
    boardThickness: 18,
    backPanelThickness: 6,
    toeKickHeight: 100,
    revealGap: 3,
    modules: [{
      width: 900,
      frontType: "drawer_stack",
      doorStyle: "flat_slab",
      doorCount: 0,
      drawerCount: 3,
      shelfCount: 1,
      materialId: "white_melamine",
      frontMaterialId: "oak_veneer",
      hardwareId: "brushed_steel_bar_pull",
      drawerBoxEnabled: true,
      drawerBoxSideThickness: CABINET_DEFAULT_DRAWER_BOX_SIDE_THICKNESS,
      drawerBoxBottomThickness: CABINET_DEFAULT_DRAWER_BOX_BOTTOM_THICKNESS,
      drawerBoxHeightClearance: CABINET_DEFAULT_DRAWER_BOX_HEIGHT_CLEARANCE,
      drawerBoxBackClearance: CABINET_DEFAULT_DRAWER_BOX_BACK_CLEARANCE,
      drawerSlideHardwareEnabled: true,
      drawerSlideLength: CABINET_DEFAULT_DRAWER_SLIDE_LENGTH,
      drawerSlideClearance: CABINET_DEFAULT_DRAWER_SLIDE_CLEARANCE,
    }],
  },
  wall: {
    name: names.wall,
    version: 1,
    units: "mm",
    totalWidth: 900,
    height: 720,
    depth: 350,
    boardThickness: 18,
    backPanelThickness: 6,
    toeKickHeight: 0,
    revealGap: 3,
    modules: [{
      width: 900,
      frontType: "double_door",
      doorStyle: "flat_slab",
      doorCount: 2,
      drawerCount: 0,
      shelfCount: 2,
      materialId: "white_melamine",
      frontMaterialId: "painted_shaker_white",
      hardwareId: "black_bar_pull",
      hingeSide: "double",
      doorHingeHardwareEnabled: true,
      doorHingeCountPerDoor: CABINET_DEFAULT_DOOR_HINGE_COUNT_PER_DOOR,
      doorHingeInsetFromTopBottom: CABINET_DEFAULT_DOOR_HINGE_INSET_FROM_TOP_BOTTOM,
      installationCleatEnabled: true,
      installationCleatHeight: CABINET_DEFAULT_INSTALLATION_CLEAT_HEIGHT,
      installationCleatThickness: CABINET_DEFAULT_INSTALLATION_CLEAT_THICKNESS,
      installationCleatInsetFromTop: CABINET_DEFAULT_INSTALLATION_CLEAT_INSET_FROM_TOP,
    }],
  },
  tall: {
    name: names.tall,
    version: 1,
    units: "mm",
    totalWidth: 600,
    height: 2200,
    depth: 580,
    boardThickness: 18,
    backPanelThickness: 6,
    toeKickHeight: 100,
    revealGap: 3,
    modules: [{
      width: 600,
      frontType: "double_door",
      doorStyle: "flat_slab",
      doorCount: 2,
      drawerCount: 0,
      shelfCount: 5,
      materialId: "white_melamine",
      frontMaterialId: "walnut_veneer",
      hardwareId: "brushed_steel_bar_pull",
      hingeSide: "double",
      antiTipAnchorEnabled: true,
      antiTipAnchorCount: CABINET_DEFAULT_ANTI_TIP_ANCHOR_COUNT,
      antiTipAnchorHeight: 2020,
      antiTipAnchorInsetFromSides: CABINET_DEFAULT_ANTI_TIP_ANCHOR_INSET_FROM_SIDES,
    }],
  },
  wardrobe: {
    name: names.wardrobe,
    version: 1,
    units: "mm",
    totalWidth: 1200,
    height: 2400,
    depth: 620,
    boardThickness: 18,
    backPanelThickness: 6,
    toeKickHeight: 80,
    revealGap: 3,
    modules: [{
      width: 1200,
      frontType: "double_door",
      doorStyle: "flat_slab",
      doorCount: 2,
      drawerCount: 0,
      shelfCount: 4,
      hangingRodCount: 1,
      hangingRodHeight: 1700,
      hamperPullOutEnabled: true,
      hamperBasketCount: CABINET_DEFAULT_HAMPER_BASKET_COUNT,
      hamperBasketDepth: CABINET_DEFAULT_HAMPER_BASKET_DEPTH,
      hamperBasketHeight: CABINET_DEFAULT_HAMPER_BASKET_HEIGHT,
      hamperSlideClearance: CABINET_DEFAULT_HAMPER_SLIDE_CLEARANCE,
      materialId: "white_melamine",
      frontMaterialId: "matte_black_laminate",
      hardwareId: "edge_pull",
      hingeSide: "double",
      antiTipAnchorEnabled: true,
      antiTipAnchorCount: CABINET_DEFAULT_ANTI_TIP_ANCHOR_COUNT,
      antiTipAnchorHeight: 2220,
      antiTipAnchorInsetFromSides: CABINET_DEFAULT_ANTI_TIP_ANCHOR_INSET_FROM_SIDES,
    }],
  },
  vanity: {
    name: names.vanity,
    version: 1,
    units: "mm",
    totalWidth: 790,
    height: 658,
    depth: 525,
    boardThickness: 18,
    backPanelThickness: 6,
    toeKickHeight: 80,
    revealGap: 3,
    includeCountertop: true,
    countertopThickness: 38,
    countertopOverhangLeft: 20,
    countertopOverhangRight: 20,
    countertopOverhangFront: 25,
    countertopOverhangBack: 0,
    countertopMaterialId: "painted_shaker_white",
    modules: [{
      width: 750,
      height: 620,
      depth: 500,
      frontType: "door_and_drawer",
      doorStyle: "flat_slab",
      doorCount: 2,
      drawerCount: 1,
      shelfCount: 1,
      sinkCutoutEnabled: true,
      sinkCutoutWidth: 480,
      sinkCutoutDepth: 340,
      sinkCutoutOffsetX: 0,
      sinkCutoutOffsetZ: 250,
      plumbingChaseWidth: 360,
      plumbingChaseHeight: 420,
      plumbingChaseDepth: 90,
      materialId: "white_melamine",
      frontMaterialId: "oak_veneer",
      hardwareId: "round_knob",
      hingeSide: "double",
    }],
  },
  tv_console: {
    name: names.tv_console,
    version: 1,
    units: "mm",
    totalWidth: 1600,
    height: 480,
    depth: 420,
    boardThickness: 18,
    backPanelThickness: 6,
    toeKickHeight: 40,
    revealGap: 3,
    modules: [{
      width: 1600,
      frontType: "slab_panel",
      doorStyle: "flat_slab",
      doorCount: 2,
      drawerCount: 0,
      shelfCount: 1,
      materialId: "white_melamine",
      frontMaterialId: "walnut_veneer",
      hardwareId: "push_to_open",
    }],
  },
  cabinet_run: {
    name: names.cabinet_run,
    version: 1,
    units: "mm",
    totalWidth: 2400,
    height: 720,
    depth: 580,
    boardThickness: 18,
    backPanelThickness: 6,
    toeKickHeight: 100,
    revealGap: 3,
    modules: [
      {
        width: 800,
        frontType: "drawer_stack",
        doorStyle: "flat_slab",
        doorCount: 0,
        drawerCount: 3,
        shelfCount: 1,
        materialId: "white_melamine",
        frontMaterialId: "oak_veneer",
        hardwareId: "brushed_steel_bar_pull",
      },
      {
        width: 800,
        frontType: "double_door",
        doorStyle: "flat_slab",
        doorCount: 2,
        drawerCount: 0,
        shelfCount: 2,
        materialId: "white_melamine",
        frontMaterialId: "painted_shaker_white",
        hardwareId: "black_bar_pull",
        hingeSide: "double",
      },
      {
        width: 800,
        frontType: "door_and_drawer",
        doorStyle: "flat_slab",
        doorCount: 2,
        drawerCount: 1,
        shelfCount: 1,
        materialId: "white_melamine",
        frontMaterialId: "walnut_veneer",
        hardwareId: "edge_pull",
        hingeSide: "double",
      },
    ],
  },
  closet_system: {
    name: names.closet_system,
    version: 1,
    units: "mm",
    millworkFamily: "closet",
    millworkAssemblyType: "closet_system",
    totalWidth: 1800,
    height: 2400,
    depth: 600,
    boardThickness: 18,
    backPanelThickness: 6,
    toeKickHeight: 80,
    revealGap: 3,
    modules: [
      {
        width: 900,
        type: "wardrobe",
        frontType: "open",
        doorStyle: "flat_slab",
        doorCount: 0,
        drawerCount: 0,
        shelfCount: 6,
        hangingRodCount: 2,
        hangingRodHeight: 1800,
        hangingRodSpacing: 900,
        materialId: "white_melamine",
        frontMaterialId: "white_melamine",
        hardwareId: "none",
      },
      {
        width: 900,
        type: "wardrobe",
        frontType: "double_door",
        doorStyle: "flat_slab",
        doorCount: 2,
        drawerCount: 0,
        shelfCount: 4,
        hangingRodCount: 1,
        hangingRodHeight: 1700,
        materialId: "white_melamine",
        frontMaterialId: "oak_veneer",
        hardwareId: "edge_pull",
        hingeSide: "double",
      },
    ],
  },
  media_wall: {
    name: names.media_wall,
    version: 1,
    units: "mm",
    millworkFamily: "media_wall",
    millworkAssemblyType: "media_wall",
    totalWidth: 3000,
    height: 2100,
    depth: 420,
    boardThickness: 18,
    backPanelThickness: 6,
    toeKickHeight: 60,
    revealGap: 3,
    modules: [
      {
        width: 600,
        type: "tall",
        frontType: "double_door",
        doorStyle: "flat_slab",
        doorCount: 2,
        drawerCount: 0,
        shelfCount: 4,
        materialId: "white_melamine",
        frontMaterialId: "walnut_veneer",
        hardwareId: "edge_pull",
        hingeSide: "double",
      },
      {
        width: 1800,
        type: "tv_console",
        height: 520,
        frontType: "slab_panel",
        doorStyle: "flat_slab",
        doorCount: 3,
        drawerCount: 0,
        shelfCount: 1,
        mediaWallEnabled: true,
        mediaTvOpeningWidth: CABINET_DEFAULT_MEDIA_TV_OPENING_WIDTH,
        mediaTvOpeningHeight: CABINET_DEFAULT_MEDIA_TV_OPENING_HEIGHT,
        mediaTvMountHeight: CABINET_DEFAULT_MEDIA_TV_MOUNT_HEIGHT,
        mediaTvBlockingThickness: CABINET_DEFAULT_MEDIA_TV_BLOCKING_THICKNESS,
        mediaCableChaseWidth: CABINET_DEFAULT_MEDIA_CABLE_CHASE_WIDTH,
        mediaCableChaseHeight: CABINET_DEFAULT_MEDIA_CABLE_CHASE_HEIGHT,
        mediaCableChaseDepth: CABINET_DEFAULT_MEDIA_CABLE_CHASE_DEPTH,
        mediaVentSlotCount: CABINET_DEFAULT_MEDIA_VENT_SLOT_COUNT,
        mediaVentSlotWidth: CABINET_DEFAULT_MEDIA_VENT_SLOT_WIDTH,
        mediaVentSlotHeight: CABINET_DEFAULT_MEDIA_VENT_SLOT_HEIGHT,
        mediaVentSlotSpacing: CABINET_DEFAULT_MEDIA_VENT_SLOT_SPACING,
        materialId: "white_melamine",
        frontMaterialId: "matte_black_laminate",
        hardwareId: "push_to_open",
      },
      {
        width: 600,
        type: "tall",
        frontType: "open",
        doorStyle: "flat_slab",
        doorCount: 0,
        drawerCount: 0,
        shelfCount: 5,
        materialId: "white_melamine",
        frontMaterialId: "white_melamine",
        hardwareId: "none",
      },
    ],
  },
  mudroom_storage: {
    name: names.mudroom_storage,
    version: 1,
    units: "mm",
    millworkFamily: "mudroom",
    millworkAssemblyType: "mudroom_storage",
    totalWidth: 2400,
    height: 2100,
    depth: 450,
    boardThickness: 18,
    backPanelThickness: 6,
    toeKickHeight: 60,
    revealGap: 3,
    modules: [
      {
        width: 600,
        type: "tall",
        frontType: "single_door",
        doorStyle: "flat_slab",
        doorCount: 1,
        drawerCount: 0,
        shelfCount: 4,
        materialId: "white_melamine",
        frontMaterialId: "painted_shaker_white",
        hardwareId: "black_bar_pull",
        hingeSide: "left",
      },
      {
        width: 1200,
        type: "base",
        height: 520,
        frontType: "open",
        doorStyle: "flat_slab",
        doorCount: 0,
        drawerCount: 0,
        shelfCount: 0,
        mudroomHookCount: 4,
        mudroomHookRailHeight: 1450,
        mudroomHookProjection: 55,
        shoeCubbyCount: 4,
        shoeCubbyHeight: 170,
        shoeCubbyDepth: 360,
        shoeCubbyDividerThickness: 18,
        materialId: "white_melamine",
        frontMaterialId: "oak_veneer",
        hardwareId: "none",
      },
      {
        width: 600,
        type: "tall",
        frontType: "single_door",
        doorStyle: "flat_slab",
        doorCount: 1,
        drawerCount: 0,
        shelfCount: 4,
        materialId: "white_melamine",
        frontMaterialId: "painted_shaker_white",
        hardwareId: "black_bar_pull",
        hingeSide: "right",
      },
    ],
  },
  laundry_room: {
    name: names.laundry_room,
    version: 1,
    units: "mm",
    millworkFamily: "laundry_room",
    millworkAssemblyType: "laundry_room_cabinetry",
    totalWidth: 2400,
    height: 900,
    depth: 600,
    boardThickness: 18,
    backPanelThickness: 6,
    toeKickHeight: 100,
    revealGap: 3,
    modules: [
      {
        width: 600,
        type: "base",
        frontType: "double_door",
        doorStyle: "flat_slab",
        doorCount: 2,
        drawerCount: 0,
        shelfCount: 1,
        materialId: "white_melamine",
        frontMaterialId: "painted_shaker_white",
        hardwareId: "black_bar_pull",
        hingeSide: "double",
      },
      {
        width: 1200,
        type: "base",
        frontType: "open",
        doorStyle: "flat_slab",
        doorCount: 0,
        drawerCount: 0,
        shelfCount: 0,
        laundryApplianceBayEnabled: true,
        laundryApplianceKind: "washer_dryer",
        laundryApplianceCount: 2,
        laundryApplianceWidth: 570,
        laundryApplianceHeight: 850,
        laundryApplianceDepth: 560,
        laundryApplianceSideClearance: 20,
        laundryApplianceTopClearance: 40,
        laundryApplianceBackClearance: 40,
        laundryUtilityChaseHeight: 180,
        laundryUtilityChaseDepth: 80,
        materialId: "white_melamine",
        frontMaterialId: "oak_veneer",
        hardwareId: "none",
      },
      {
        width: 600,
        type: "base",
        frontType: "double_door",
        doorStyle: "flat_slab",
        doorCount: 2,
        drawerCount: 0,
        shelfCount: 1,
        materialId: "white_melamine",
        frontMaterialId: "painted_shaker_white",
        hardwareId: "black_bar_pull",
        hingeSide: "double",
      },
    ],
  },
  home_office_built_in: {
    name: names.home_office_built_in,
    version: 1,
    units: "mm",
    millworkFamily: "home_office",
    millworkAssemblyType: "home_office_built_in",
    totalWidth: 3000,
    height: 2100,
    depth: 650,
    boardThickness: 18,
    backPanelThickness: 6,
    toeKickHeight: 80,
    revealGap: 3,
    modules: [
      {
        width: 700,
        type: "tall",
        depth: 550,
        frontType: "open",
        doorStyle: "flat_slab",
        doorCount: 0,
        drawerCount: 0,
        shelfCount: 5,
        materialId: "white_melamine",
        frontMaterialId: "white_melamine",
        hardwareId: "none",
      },
      {
        width: 1600,
        type: "base",
        height: 720,
        depth: 550,
        frontType: "drawer_stack",
        doorStyle: "flat_slab",
        doorCount: 0,
        drawerCount: 3,
        shelfCount: 1,
        officeWorksurfaceEnabled: true,
        officeWorksurfaceThickness: 36,
        officeWorksurfaceDepth: 650,
        officeWorksurfaceOverhangFront: 100,
        cableGrommetCount: 3,
        cableGrommetDiameter: 80,
        cableGrommetOffsetFromBack: 110,
        deskPowerChaseHeight: 120,
        deskPowerChaseDepth: 60,
        materialId: "white_melamine",
        frontMaterialId: "walnut_veneer",
        hardwareId: "brushed_steel_bar_pull",
      },
      {
        width: 700,
        type: "tall",
        depth: 550,
        frontType: "open",
        doorStyle: "flat_slab",
        doorCount: 0,
        drawerCount: 0,
        shelfCount: 5,
        materialId: "white_melamine",
        frontMaterialId: "white_melamine",
        hardwareId: "none",
      },
    ],
  },
  library_wall: {
    name: names.library_wall,
    version: 1,
    units: "mm",
    millworkFamily: "library",
    millworkAssemblyType: "library_wall",
    totalWidth: 3000,
    height: 2400,
    depth: 350,
    boardThickness: 18,
    backPanelThickness: 6,
    toeKickHeight: 60,
    revealGap: 3,
    modules: [
      {
        width: 1000,
        type: "wall",
        frontType: "open",
        doorStyle: "flat_slab",
        doorCount: 0,
        drawerCount: 0,
        shelfCount: 7,
        libraryLadderRailEnabled: true,
        libraryLadderRailHeight: CABINET_DEFAULT_LIBRARY_LADDER_RAIL_HEIGHT,
        libraryLadderRailDiameter: CABINET_DEFAULT_LIBRARY_LADDER_RAIL_DIAMETER,
        libraryLadderRailProjection: CABINET_DEFAULT_LIBRARY_LADDER_RAIL_PROJECTION,
        libraryLadderStandoffCount: CABINET_DEFAULT_LIBRARY_LADDER_STANDOFF_COUNT,
        libraryLadderStandoffDiameter: CABINET_DEFAULT_LIBRARY_LADDER_STANDOFF_DIAMETER,
        lightingChannelEnabled: true,
        lightingChannelCount: CABINET_DEFAULT_LIGHTING_CHANNEL_COUNT,
        lightingChannelDepth: CABINET_DEFAULT_LIGHTING_CHANNEL_DEPTH,
        lightingChannelHeight: CABINET_DEFAULT_LIGHTING_CHANNEL_HEIGHT,
        lightingChannelInsetFromFront: CABINET_DEFAULT_LIGHTING_CHANNEL_INSET_FROM_FRONT,
        shelfPinRowsEnabled: true,
        shelfPinRowPairCount: CABINET_DEFAULT_SHELF_PIN_ROW_PAIR_COUNT,
        shelfPinHoleCount: CABINET_DEFAULT_SHELF_PIN_HOLE_COUNT,
        shelfPinHoleSpacing: CABINET_DEFAULT_SHELF_PIN_HOLE_SPACING,
        shelfPinInsetFromFront: CABINET_DEFAULT_SHELF_PIN_INSET_FROM_FRONT,
        shelfPinStartHeight: CABINET_DEFAULT_SHELF_PIN_START_HEIGHT,
        materialId: "white_melamine",
        frontMaterialId: "white_melamine",
        hardwareId: "none",
      },
      {
        width: 1000,
        type: "wall",
        frontType: "open",
        doorStyle: "flat_slab",
        doorCount: 0,
        drawerCount: 0,
        shelfCount: 7,
        libraryLadderRailEnabled: true,
        libraryLadderRailHeight: CABINET_DEFAULT_LIBRARY_LADDER_RAIL_HEIGHT,
        libraryLadderRailDiameter: CABINET_DEFAULT_LIBRARY_LADDER_RAIL_DIAMETER,
        libraryLadderRailProjection: CABINET_DEFAULT_LIBRARY_LADDER_RAIL_PROJECTION,
        libraryLadderStandoffCount: CABINET_DEFAULT_LIBRARY_LADDER_STANDOFF_COUNT,
        libraryLadderStandoffDiameter: CABINET_DEFAULT_LIBRARY_LADDER_STANDOFF_DIAMETER,
        lightingChannelEnabled: true,
        lightingChannelCount: CABINET_DEFAULT_LIGHTING_CHANNEL_COUNT,
        lightingChannelDepth: CABINET_DEFAULT_LIGHTING_CHANNEL_DEPTH,
        lightingChannelHeight: CABINET_DEFAULT_LIGHTING_CHANNEL_HEIGHT,
        lightingChannelInsetFromFront: CABINET_DEFAULT_LIGHTING_CHANNEL_INSET_FROM_FRONT,
        shelfPinRowsEnabled: true,
        shelfPinRowPairCount: CABINET_DEFAULT_SHELF_PIN_ROW_PAIR_COUNT,
        shelfPinHoleCount: CABINET_DEFAULT_SHELF_PIN_HOLE_COUNT,
        shelfPinHoleSpacing: CABINET_DEFAULT_SHELF_PIN_HOLE_SPACING,
        shelfPinInsetFromFront: CABINET_DEFAULT_SHELF_PIN_INSET_FROM_FRONT,
        shelfPinStartHeight: CABINET_DEFAULT_SHELF_PIN_START_HEIGHT,
        materialId: "white_melamine",
        frontMaterialId: "white_melamine",
        hardwareId: "none",
      },
      {
        width: 1000,
        type: "wall",
        frontType: "open",
        doorStyle: "flat_slab",
        doorCount: 0,
        drawerCount: 0,
        shelfCount: 7,
        libraryLadderRailEnabled: true,
        libraryLadderRailHeight: CABINET_DEFAULT_LIBRARY_LADDER_RAIL_HEIGHT,
        libraryLadderRailDiameter: CABINET_DEFAULT_LIBRARY_LADDER_RAIL_DIAMETER,
        libraryLadderRailProjection: CABINET_DEFAULT_LIBRARY_LADDER_RAIL_PROJECTION,
        libraryLadderStandoffCount: CABINET_DEFAULT_LIBRARY_LADDER_STANDOFF_COUNT,
        libraryLadderStandoffDiameter: CABINET_DEFAULT_LIBRARY_LADDER_STANDOFF_DIAMETER,
        lightingChannelEnabled: true,
        lightingChannelCount: CABINET_DEFAULT_LIGHTING_CHANNEL_COUNT,
        lightingChannelDepth: CABINET_DEFAULT_LIGHTING_CHANNEL_DEPTH,
        lightingChannelHeight: CABINET_DEFAULT_LIGHTING_CHANNEL_HEIGHT,
        lightingChannelInsetFromFront: CABINET_DEFAULT_LIGHTING_CHANNEL_INSET_FROM_FRONT,
        shelfPinRowsEnabled: true,
        shelfPinRowPairCount: CABINET_DEFAULT_SHELF_PIN_ROW_PAIR_COUNT,
        shelfPinHoleCount: CABINET_DEFAULT_SHELF_PIN_HOLE_COUNT,
        shelfPinHoleSpacing: CABINET_DEFAULT_SHELF_PIN_HOLE_SPACING,
        shelfPinInsetFromFront: CABINET_DEFAULT_SHELF_PIN_INSET_FROM_FRONT,
        shelfPinStartHeight: CABINET_DEFAULT_SHELF_PIN_START_HEIGHT,
        materialId: "white_melamine",
        frontMaterialId: "white_melamine",
        hardwareId: "none",
      },
    ],
  },
  window_seat: {
    name: names.window_seat,
    version: 1,
    units: "mm",
    millworkFamily: "window_seat",
    millworkAssemblyType: "window_seat",
    totalWidth: 1800,
    height: 480,
    depth: 520,
    boardThickness: 18,
    backPanelThickness: 6,
    toeKickHeight: 40,
    revealGap: 3,
    modules: [
      {
        width: 900,
        type: "base",
        height: 380,
        frontType: "slab_panel",
        doorStyle: "flat_slab",
        doorCount: 1,
        drawerCount: 0,
        shelfCount: 1,
        seatDeckThickness: 24,
        seatCushionThickness: 75,
        seatCushionDepth: 540,
        seatCushionOverhangFront: 20,
        materialId: "white_melamine",
        frontMaterialId: "oak_veneer",
        hardwareId: "push_to_open",
      },
      {
        width: 900,
        type: "base",
        height: 380,
        frontType: "slab_panel",
        doorStyle: "flat_slab",
        doorCount: 1,
        drawerCount: 0,
        shelfCount: 1,
        seatDeckThickness: 24,
        seatCushionThickness: 75,
        seatCushionDepth: 540,
        seatCushionOverhangFront: 20,
        materialId: "white_melamine",
        frontMaterialId: "oak_veneer",
        hardwareId: "push_to_open",
      },
    ],
  },
  banquette: {
    name: names.banquette,
    version: 1,
    units: "mm",
    millworkFamily: "banquette",
    millworkAssemblyType: "banquette",
    totalWidth: 2200,
    height: 820,
    depth: 580,
    boardThickness: 18,
    backPanelThickness: 6,
    toeKickHeight: 40,
    revealGap: 3,
    modules: [
      {
        width: 1100,
        type: "base",
        height: 360,
        frontType: "slab_panel",
        doorStyle: "flat_slab",
        doorCount: 1,
        drawerCount: 0,
        shelfCount: 1,
        seatDeckThickness: 24,
        seatCushionThickness: 80,
        seatCushionDepth: 610,
        seatCushionOverhangFront: 30,
        seatBackHeight: 420,
        seatBackThickness: 24,
        materialId: "white_melamine",
        frontMaterialId: "walnut_veneer",
        hardwareId: "push_to_open",
      },
      {
        width: 1100,
        type: "base",
        height: 360,
        frontType: "slab_panel",
        doorStyle: "flat_slab",
        doorCount: 1,
        drawerCount: 0,
        shelfCount: 1,
        seatDeckThickness: 24,
        seatCushionThickness: 80,
        seatCushionDepth: 610,
        seatCushionOverhangFront: 30,
        seatBackHeight: 420,
        seatBackThickness: 24,
        materialId: "white_melamine",
        frontMaterialId: "walnut_veneer",
        hardwareId: "push_to_open",
      },
    ],
  },
  murphy_bed: {
    name: names.murphy_bed,
    version: 1,
    units: "mm",
    millworkFamily: "murphy_bed",
    millworkAssemblyType: "murphy_bed",
    totalWidth: 2200,
    height: 2300,
    depth: 450,
    boardThickness: 18,
    backPanelThickness: 6,
    toeKickHeight: 60,
    revealGap: 3,
    modules: [
      {
        width: 375,
        type: "tall",
        frontType: "open",
        doorStyle: "flat_slab",
        doorCount: 0,
        drawerCount: 0,
        shelfCount: 5,
        materialId: "white_melamine",
        frontMaterialId: "white_melamine",
        hardwareId: "none",
      },
      {
        width: 1450,
        type: "wardrobe",
        millworkComponentType: "wall_bed_panel",
        frontType: "open",
        doorStyle: "flat_slab",
        doorCount: 0,
        drawerCount: 0,
        shelfCount: 0,
        convertiblePanelThickness: 42,
        convertiblePanelHeight: 2200,
        convertibleOpenDepth: 2050,
        convertibleHingeHeight: 90,
        convertibleSupportLegCount: 2,
        convertibleSupportLegWidth: 45,
        convertibleSupportLegDepth: 45,
        wallBedMattressSize: "double",
        wallBedOrientation: "vertical",
        wallBedDisplayState: "closed",
        wallBedClearanceVisible: true,
        wallBedSideStorage: "both",
        materialId: "white_melamine",
        frontMaterialId: "walnut_veneer",
        hardwareId: "edge_pull",
      },
      {
        width: 375,
        type: "tall",
        frontType: "open",
        doorStyle: "flat_slab",
        doorCount: 0,
        drawerCount: 0,
        shelfCount: 5,
        materialId: "white_melamine",
        frontMaterialId: "white_melamine",
        hardwareId: "none",
      },
    ],
  },
  fold_down_desk: {
    name: names.fold_down_desk,
    version: 1,
    units: "mm",
    millworkFamily: "home_office",
    millworkAssemblyType: "fold_down_desk",
    totalWidth: 1200,
    height: 1500,
    depth: 320,
    boardThickness: 18,
    backPanelThickness: 6,
    toeKickHeight: 0,
    revealGap: 3,
    modules: [
      {
        width: 1200,
        type: "wall",
        millworkComponentType: "fold_down_worksurface",
        frontType: "open",
        doorStyle: "flat_slab",
        doorCount: 0,
        drawerCount: 0,
        shelfCount: 0,
        convertiblePanelThickness: 30,
        convertiblePanelHeight: 720,
        convertibleOpenDepth: 650,
        convertibleHingeHeight: 740,
        convertibleSupportLegCount: 2,
        convertibleSupportLegWidth: 35,
        convertibleSupportLegDepth: 35,
        materialId: "white_melamine",
        frontMaterialId: "oak_veneer",
        hardwareId: "edge_pull",
      },
    ],
  },
  platform_storage_bed: {
    name: names.platform_storage_bed,
    version: 1,
    units: "mm",
    millworkFamily: "storage_bed",
    millworkAssemblyType: "platform_storage_bed",
    totalWidth: 2400,
    height: 420,
    depth: 1040,
    boardThickness: 18,
    backPanelThickness: 6,
    toeKickHeight: 40,
    revealGap: 3,
    modules: [
      {
        width: 1200,
        depth: 1000,
        type: "base",
        frontType: "drawer_stack",
        doorStyle: "flat_slab",
        doorCount: 0,
        drawerCount: 2,
        shelfCount: 0,
        platformDeckThickness: 24,
        platformDeckOverhangFront: 20,
        platformDeckOverhangBack: 20,
        platformSupportRibCount: 3,
        platformSupportRibWidth: 70,
        platformSupportRibHeight: 90,
        materialId: "white_melamine",
        frontMaterialId: "oak_veneer",
        hardwareId: "edge_pull",
      },
      {
        width: 1200,
        depth: 1000,
        type: "base",
        frontType: "drawer_stack",
        doorStyle: "flat_slab",
        doorCount: 0,
        drawerCount: 2,
        shelfCount: 0,
        platformDeckThickness: 24,
        platformDeckOverhangFront: 20,
        platformDeckOverhangBack: 20,
        platformSupportRibCount: 3,
        platformSupportRibWidth: 70,
        platformSupportRibHeight: 90,
        materialId: "white_melamine",
        frontMaterialId: "oak_veneer",
        hardwareId: "edge_pull",
      },
    ],
  },
  under_stair_storage: {
    name: names.under_stair_storage,
    version: 1,
    units: "mm",
    millworkFamily: "under_stair_storage",
    millworkAssemblyType: "under_stair_storage",
    totalWidth: 1800,
    height: 1800,
    depth: 600,
    boardThickness: 18,
    backPanelThickness: 6,
    toeKickHeight: 60,
    revealGap: 3,
    modules: [
      {
        width: 600,
        type: "tall",
        height: 1800,
        frontType: "single_door",
        doorStyle: "flat_slab",
        doorCount: 1,
        drawerCount: 0,
        shelfCount: 4,
        materialId: "white_melamine",
        frontMaterialId: "painted_shaker_white",
        hardwareId: "black_bar_pull",
        hingeSide: "left",
      },
      {
        width: 600,
        type: "tall",
        height: 1350,
        frontType: "single_door",
        doorStyle: "flat_slab",
        doorCount: 1,
        drawerCount: 0,
        shelfCount: 3,
        stairScribeStepCount: 3,
        stairScribeHighHeight: 1800,
        stairScribeLowHeight: 1500,
        stairScribeDepth: 24,
        stairScribeDirection: "rises_left",
        materialId: "white_melamine",
        frontMaterialId: "painted_shaker_white",
        hardwareId: "black_bar_pull",
        hingeSide: "left",
      },
      {
        width: 600,
        type: "base",
        height: 900,
        frontType: "drawer_stack",
        doorStyle: "flat_slab",
        doorCount: 0,
        drawerCount: 3,
        shelfCount: 0,
        stairScribeStepCount: 3,
        stairScribeHighHeight: 1500,
        stairScribeLowHeight: 1050,
        stairScribeDepth: 24,
        stairScribeDirection: "rises_left",
        materialId: "white_melamine",
        frontMaterialId: "oak_veneer",
        hardwareId: "edge_pull",
      },
    ],
  },
  room_divider_storage: {
    name: names.room_divider_storage,
    version: 1,
    units: "mm",
    millworkFamily: "room_divider_storage",
    millworkAssemblyType: "room_divider_storage",
    totalWidth: 2400,
    height: 1800,
    depth: 360,
    boardThickness: 18,
    backPanelThickness: 6,
    toeKickHeight: 40,
    revealGap: 3,
    modules: [
      {
        width: 800,
        type: "wall",
        frontType: "open",
        doorStyle: "flat_slab",
        doorCount: 0,
        drawerCount: 0,
        shelfCount: 5,
        roomDividerFinishedBack: true,
        roomDividerBackPanelCount: 2,
        roomDividerBackPanelThickness: 18,
        roomDividerStabilizerFootCount: 2,
        roomDividerStabilizerFootWidth: 90,
        roomDividerStabilizerFootHeight: 45,
        roomDividerStabilizerFootDepth: 360,
        materialId: "white_melamine",
        frontMaterialId: "white_melamine",
        hardwareId: "none",
      },
      {
        width: 800,
        type: "wall",
        frontType: "slab_panel",
        doorStyle: "flat_slab",
        doorCount: 2,
        drawerCount: 0,
        shelfCount: 3,
        roomDividerFinishedBack: true,
        roomDividerBackPanelCount: 2,
        roomDividerBackPanelThickness: 18,
        roomDividerStabilizerFootCount: 2,
        roomDividerStabilizerFootWidth: 90,
        roomDividerStabilizerFootHeight: 45,
        roomDividerStabilizerFootDepth: 360,
        materialId: "white_melamine",
        frontMaterialId: "walnut_veneer",
        hardwareId: "push_to_open",
      },
      {
        width: 800,
        type: "wall",
        frontType: "open",
        doorStyle: "flat_slab",
        doorCount: 0,
        drawerCount: 0,
        shelfCount: 5,
        roomDividerFinishedBack: true,
        roomDividerBackPanelCount: 2,
        roomDividerBackPanelThickness: 18,
        roomDividerStabilizerFootCount: 2,
        roomDividerStabilizerFootWidth: 90,
        roomDividerStabilizerFootHeight: 45,
        roomDividerStabilizerFootDepth: 360,
        materialId: "white_melamine",
        frontMaterialId: "white_melamine",
        hardwareId: "none",
      },
    ],
  },
  home_bar: {
    name: names.home_bar,
    version: 1,
    units: "mm",
    millworkFamily: "bar",
    millworkAssemblyType: "home_bar",
    totalWidth: 2400,
    height: 2100,
    depth: 520,
    boardThickness: 18,
    backPanelThickness: 6,
    toeKickHeight: 80,
    revealGap: 3,
    modules: [
      {
        width: 800,
        type: "tall",
        frontType: "double_door",
        doorStyle: "glass",
        doorCount: 2,
        drawerCount: 0,
        shelfCount: 4,
        stemwareRackEnabled: true,
        stemwareRackLaneCount: CABINET_DEFAULT_STEMWARE_RACK_LANE_COUNT,
        stemwareRackDepth: CABINET_DEFAULT_STEMWARE_RACK_DEPTH,
        stemwareRackRailWidth: CABINET_DEFAULT_STEMWARE_RACK_RAIL_WIDTH,
        stemwareRackLaneSpacing: CABINET_DEFAULT_STEMWARE_RACK_LANE_SPACING,
        stemwareRackMountHeight: CABINET_DEFAULT_STEMWARE_RACK_MOUNT_HEIGHT,
        materialId: "white_melamine",
        frontMaterialId: "glass",
        hardwareId: "black_bar_pull",
        hingeSide: "double",
      },
      {
        width: 800,
        type: "base",
        height: 900,
        frontType: "door_and_drawer",
        doorStyle: "flat_slab",
        doorCount: 2,
        drawerCount: 1,
        shelfCount: 1,
        materialId: "white_melamine",
        frontMaterialId: "walnut_veneer",
        hardwareId: "edge_pull",
        hingeSide: "double",
      },
      {
        width: 800,
        type: "tall",
        frontType: "open",
        doorStyle: "flat_slab",
        doorCount: 0,
        drawerCount: 0,
        shelfCount: 2,
        wineRackColumnCount: 2,
        wineRackRowCount: 4,
        wineRackDepth: 460,
        wineRackDividerThickness: 18,
        materialId: "white_melamine",
        frontMaterialId: "white_melamine",
        hardwareId: "none",
      },
    ],
  },
  kitchen_island: {
    name: names.kitchen_island,
    version: 1,
    units: "mm",
    millworkFamily: "island",
    millworkAssemblyType: "kitchen_island",
    totalWidth: 2440,
    height: 900,
    depth: 1245,
    boardThickness: 18,
    backPanelThickness: 6,
    toeKickHeight: 100,
    revealGap: 3,
    includeCountertop: true,
    countertopThickness: 38,
    countertopOverhangLeft: 20,
    countertopOverhangRight: 20,
    countertopOverhangFront: 25,
    countertopOverhangBack: 320,
    countertopMaterialId: "painted_shaker_white",
    islandSeatingOverhangEnabled: true,
    islandSeatingOverhangDepth: 320,
    islandSupportPanelCount: 3,
    islandSupportPanelThickness: 36,
    islandSupportPanelDepth: 260,
    islandSupportPanelEndInset: 180,
    modules: [
      {
        width: 800,
        type: "base",
        height: 862,
        depth: 900,
        frontType: "drawer_stack",
        doorStyle: "flat_slab",
        doorCount: 0,
        drawerCount: 3,
        shelfCount: 0,
        materialId: "white_melamine",
        frontMaterialId: "oak_veneer",
        hardwareId: "brushed_steel_bar_pull",
      },
      {
        width: 800,
        type: "base",
        height: 862,
        depth: 900,
        frontType: "double_door",
        doorStyle: "flat_slab",
        doorCount: 2,
        drawerCount: 0,
        shelfCount: 2,
        materialId: "white_melamine",
        frontMaterialId: "painted_shaker_white",
        hardwareId: "black_bar_pull",
        hingeSide: "double",
      },
      {
        width: 800,
        type: "base",
        height: 862,
        depth: 900,
        frontType: "drawer_stack",
        doorStyle: "flat_slab",
        doorCount: 0,
        drawerCount: 3,
        shelfCount: 0,
        materialId: "white_melamine",
        frontMaterialId: "walnut_veneer",
        hardwareId: "edge_pull",
      },
    ],
  },
  pantry_system: {
    name: names.pantry_system,
    version: 1,
    units: "mm",
    millworkFamily: "pantry",
    millworkAssemblyType: "pantry_system",
    totalWidth: 2400,
    height: 2400,
    depth: 600,
    boardThickness: 18,
    backPanelThickness: 6,
    toeKickHeight: 80,
    revealGap: 3,
    modules: [
      {
        width: 600,
        type: "tall",
        frontType: "double_door",
        doorStyle: "flat_slab",
        doorCount: 2,
        drawerCount: 0,
        shelfCount: 2,
        pantryPullOutTrayEnabled: true,
        pantryPullOutTrayCount: 4,
        pantryPullOutTrayDepth: 520,
        pantryPullOutTrayFrontHeight: 70,
        pantryPullOutSlideClearance: 35,
        materialId: "white_melamine",
        frontMaterialId: "painted_shaker_white",
        hardwareId: "black_bar_pull",
        hingeSide: "double",
      },
      {
        width: 600,
        type: "tall",
        frontType: "drawer_stack",
        doorStyle: "flat_slab",
        doorCount: 0,
        drawerCount: 4,
        shelfCount: 1,
        materialId: "white_melamine",
        frontMaterialId: "oak_veneer",
        hardwareId: "brushed_steel_bar_pull",
      },
      {
        width: 600,
        type: "tall",
        frontType: "open",
        doorStyle: "flat_slab",
        doorCount: 0,
        drawerCount: 0,
        shelfCount: 6,
        materialId: "white_melamine",
        frontMaterialId: "white_melamine",
        hardwareId: "none",
      },
      {
        width: 600,
        type: "tall",
        frontType: "double_door",
        doorStyle: "glass",
        doorCount: 2,
        drawerCount: 0,
        shelfCount: 4,
        materialId: "white_melamine",
        frontMaterialId: "glass",
        hardwareId: "black_bar_pull",
        hingeSide: "double",
      },
    ],
  },
  wine_storage: {
    name: names.wine_storage,
    version: 1,
    units: "mm",
    millworkFamily: "wine_storage",
    millworkAssemblyType: "wine_storage",
    totalWidth: 1800,
    height: 2100,
    depth: 480,
    boardThickness: 18,
    backPanelThickness: 6,
    toeKickHeight: 60,
    revealGap: 3,
    modules: [
      {
        width: 600,
        type: "tall",
        frontType: "double_door",
        doorStyle: "glass",
        doorCount: 2,
        drawerCount: 0,
        shelfCount: 5,
        materialId: "white_melamine",
        frontMaterialId: "glass",
        hardwareId: "black_bar_pull",
        hingeSide: "double",
      },
      {
        width: 600,
        type: "tall",
        frontType: "open",
        doorStyle: "flat_slab",
        doorCount: 0,
        drawerCount: 0,
        shelfCount: 0,
        wineRackColumnCount: 3,
        wineRackRowCount: 6,
        wineRackDepth: 420,
        wineRackDividerThickness: 18,
        materialId: "walnut_veneer",
        frontMaterialId: "walnut_veneer",
        hardwareId: "none",
      },
      {
        width: 600,
        type: "base",
        height: 900,
        frontType: "door_and_drawer",
        doorStyle: "flat_slab",
        doorCount: 2,
        drawerCount: 1,
        shelfCount: 1,
        materialId: "white_melamine",
        frontMaterialId: "walnut_veneer",
        hardwareId: "edge_pull",
        hingeSide: "double",
      },
    ],
  },
  pet_built_in: {
    name: names.pet_built_in,
    version: 1,
    units: "mm",
    millworkFamily: "lifestyle_built_in",
    millworkAssemblyType: "pet_built_in",
    totalWidth: 1800,
    height: 900,
    depth: 520,
    boardThickness: 18,
    backPanelThickness: 6,
    toeKickHeight: 60,
    revealGap: 3,
    modules: [
      {
        width: 600,
        type: "base",
        frontType: "door_and_drawer",
        doorStyle: "flat_slab",
        doorCount: 2,
        drawerCount: 1,
        shelfCount: 1,
        materialId: "white_melamine",
        frontMaterialId: "painted_shaker_white",
        hardwareId: "round_knob",
        hingeSide: "double",
      },
      {
        width: 600,
        type: "base",
        frontType: "open",
        doorStyle: "flat_slab",
        doorCount: 0,
        drawerCount: 0,
        shelfCount: 1,
        lifestyleInsertKind: "pet_bed",
        lifestyleInsertCount: 1,
        lifestyleInsertDepth: 460,
        lifestyleInsertDeckHeight: 24,
        lifestyleInsertLipHeight: 80,
        materialId: "white_melamine",
        frontMaterialId: "oak_veneer",
        hardwareId: "none",
      },
      {
        width: 600,
        type: "base",
        frontType: "drawer_stack",
        doorStyle: "flat_slab",
        doorCount: 0,
        drawerCount: 3,
        shelfCount: 0,
        materialId: "white_melamine",
        frontMaterialId: "oak_veneer",
        hardwareId: "brushed_steel_bar_pull",
      },
    ],
  },
  kids_storage: {
    name: names.kids_storage,
    version: 1,
    units: "mm",
    millworkFamily: "lifestyle_built_in",
    millworkAssemblyType: "kids_storage",
    totalWidth: 1800,
    height: 1200,
    depth: 450,
    boardThickness: 18,
    backPanelThickness: 6,
    toeKickHeight: 40,
    revealGap: 3,
    modules: [
      {
        width: 600,
        type: "base",
        frontType: "open",
        doorStyle: "flat_slab",
        doorCount: 0,
        drawerCount: 0,
        shelfCount: 3,
        lifestyleInsertKind: "toy_bin",
        lifestyleInsertCount: 2,
        lifestyleInsertDepth: 400,
        lifestyleInsertDeckHeight: 18,
        lifestyleInsertLipHeight: 120,
        materialId: "painted_shaker_white",
        frontMaterialId: "painted_shaker_white",
        hardwareId: "none",
      },
      {
        width: 600,
        type: "base",
        frontType: "double_door",
        doorStyle: "flat_slab",
        doorCount: 2,
        drawerCount: 0,
        shelfCount: 2,
        materialId: "white_melamine",
        frontMaterialId: "oak_veneer",
        hardwareId: "round_knob",
        hingeSide: "double",
      },
      {
        width: 600,
        type: "base",
        frontType: "open",
        doorStyle: "flat_slab",
        doorCount: 0,
        drawerCount: 0,
        shelfCount: 3,
        lifestyleInsertKind: "toy_bin",
        lifestyleInsertCount: 2,
        lifestyleInsertDepth: 400,
        lifestyleInsertDeckHeight: 18,
        lifestyleInsertLipHeight: 120,
        materialId: "painted_shaker_white",
        frontMaterialId: "painted_shaker_white",
        hardwareId: "none",
      },
    ],
  },
  hobby_storage: {
    name: names.hobby_storage,
    version: 1,
    units: "mm",
    millworkFamily: "lifestyle_built_in",
    millworkAssemblyType: "hobby_storage",
    totalWidth: 2400,
    height: 1800,
    depth: 520,
    boardThickness: 18,
    backPanelThickness: 6,
    toeKickHeight: 60,
    revealGap: 3,
    modules: [
      {
        width: 600,
        type: "tall",
        frontType: "double_door",
        doorStyle: "flat_slab",
        doorCount: 2,
        drawerCount: 0,
        shelfCount: 4,
        materialId: "white_melamine",
        frontMaterialId: "matte_black_laminate",
        hardwareId: "edge_pull",
        hingeSide: "double",
      },
      {
        width: 1200,
        type: "base",
        height: 900,
        frontType: "drawer_stack",
        doorStyle: "flat_slab",
        doorCount: 0,
        drawerCount: 4,
        shelfCount: 0,
        materialId: "white_melamine",
        frontMaterialId: "painted_shaker_white",
        hardwareId: "black_bar_pull",
      },
      {
        width: 600,
        type: "tall",
        frontType: "open",
        doorStyle: "flat_slab",
        doorCount: 0,
        drawerCount: 0,
        shelfCount: 5,
        lifestyleInsertKind: "hobby_tray",
        lifestyleInsertCount: 3,
        lifestyleInsertDepth: 460,
        lifestyleInsertDeckHeight: 18,
        lifestyleInsertLipHeight: 70,
        materialId: "white_melamine",
        frontMaterialId: "white_melamine",
        hardwareId: "none",
      },
    ],
  },
  wall_paneling: {
    name: names.wall_paneling,
    version: 1,
    units: "mm",
    millworkFamily: "paneling",
    millworkAssemblyType: "wall_paneling",
    totalWidth: 2400,
    height: 1200,
    depth: 80,
    boardThickness: 18,
    backPanelThickness: 6,
    toeKickHeight: 0,
    revealGap: 3,
    modules: [
      {
        width: 600,
        type: "wall",
        frontType: "slab_panel",
        doorStyle: "shaker",
        doorCount: 1,
        drawerCount: 0,
        shelfCount: 0,
        panelColumnCount: 1,
        panelRowCount: 2,
        panelFrameWidth: 55,
        panelFrameDepth: 18,
        materialId: "painted_shaker_white",
        frontMaterialId: "painted_shaker_white",
        hardwareId: "none",
      },
      {
        width: 600,
        type: "wall",
        frontType: "slab_panel",
        doorStyle: "shaker",
        doorCount: 1,
        drawerCount: 0,
        shelfCount: 0,
        panelColumnCount: 1,
        panelRowCount: 2,
        panelFrameWidth: 55,
        panelFrameDepth: 18,
        materialId: "painted_shaker_white",
        frontMaterialId: "painted_shaker_white",
        hardwareId: "none",
      },
      {
        width: 600,
        type: "wall",
        frontType: "slab_panel",
        doorStyle: "shaker",
        doorCount: 1,
        drawerCount: 0,
        shelfCount: 0,
        panelColumnCount: 1,
        panelRowCount: 2,
        panelFrameWidth: 55,
        panelFrameDepth: 18,
        materialId: "painted_shaker_white",
        frontMaterialId: "painted_shaker_white",
        hardwareId: "none",
      },
      {
        width: 600,
        type: "wall",
        frontType: "slab_panel",
        doorStyle: "shaker",
        doorCount: 1,
        drawerCount: 0,
        shelfCount: 0,
        panelColumnCount: 1,
        panelRowCount: 2,
        panelFrameWidth: 55,
        panelFrameDepth: 18,
        materialId: "painted_shaker_white",
        frontMaterialId: "painted_shaker_white",
        hardwareId: "none",
      },
    ],
  },
  slat_wall: {
    name: names.slat_wall,
    version: 1,
    units: "mm",
    millworkFamily: "paneling",
    millworkAssemblyType: "slat_wall",
    totalWidth: 1800,
    height: 2400,
    depth: 90,
    boardThickness: 18,
    backPanelThickness: 6,
    toeKickHeight: 0,
    revealGap: 3,
    modules: Array.from({ length: 6 }, () => ({
      width: 300,
      type: "wall",
      frontType: "slab_panel",
      doorStyle: "fluted",
      doorCount: 1,
      drawerCount: 0,
      shelfCount: 0,
      slatCount: 4,
      slatWidth: 32,
      slatDepth: 38,
      materialId: "walnut_veneer",
      frontMaterialId: "walnut_veneer",
      hardwareId: "none",
    })),
  },
  ceiling_beams: {
    name: names.ceiling_beams,
    version: 1,
    units: "mm",
    millworkFamily: "ceiling_woodwork",
    millworkAssemblyType: "ceiling_beams",
    totalWidth: 3000,
    height: 180,
    depth: 2400,
    boardThickness: 18,
    backPanelThickness: 6,
    toeKickHeight: 0,
    revealGap: 3,
    modules: [
      {
        width: 3000,
        type: "wall",
        millworkComponentType: "ceiling_beam_array",
        frontType: "open",
        doorStyle: "flat_slab",
        doorCount: 0,
        drawerCount: 0,
        shelfCount: 0,
        ceilingBeamCount: 4,
        ceilingBeamWidth: 160,
        ceilingBeamDepth: 180,
        ceilingBeamOrientation: "z",
        materialId: "walnut_veneer",
        frontMaterialId: "walnut_veneer",
        hardwareId: "none",
      },
    ],
  },
  coffered_ceiling: {
    name: names.coffered_ceiling,
    version: 1,
    units: "mm",
    millworkFamily: "ceiling_woodwork",
    millworkAssemblyType: "coffered_ceiling",
    totalWidth: 2400,
    height: 220,
    depth: 2400,
    boardThickness: 18,
    backPanelThickness: 6,
    toeKickHeight: 0,
    revealGap: 3,
    modules: [
      {
        width: 2400,
        type: "wall",
        millworkComponentType: "coffered_ceiling_grid",
        frontType: "open",
        doorStyle: "shaker",
        doorCount: 0,
        drawerCount: 0,
        shelfCount: 0,
        ceilingGridColumnCount: 3,
        ceilingGridRowCount: 3,
        ceilingBeamWidth: 120,
        ceilingBeamDepth: 220,
        materialId: "painted_shaker_white",
        frontMaterialId: "painted_shaker_white",
        hardwareId: "none",
      },
    ],
  },
  fireplace_surround: {
    name: names.fireplace_surround,
    version: 1,
    units: "mm",
    millworkFamily: "trim",
    millworkAssemblyType: "fireplace_surround",
    totalWidth: 2400,
    height: 2100,
    depth: 220,
    boardThickness: 18,
    backPanelThickness: 6,
    toeKickHeight: 0,
    revealGap: 3,
    modules: [
      {
        width: 2400,
        type: "wall",
        millworkComponentType: "fireplace_surround_frame",
        frontType: "open",
        doorStyle: "flat_slab",
        doorCount: 0,
        drawerCount: 0,
        shelfCount: 0,
        fireplaceOpeningWidth: 1100,
        fireplaceOpeningHeight: 900,
        fireplaceLegWidth: 180,
        fireplaceHeaderHeight: 220,
        fireplaceMantelHeight: 120,
        fireplaceMantelDepth: 300,
        materialId: "painted_shaker_white",
        frontMaterialId: "painted_shaker_white",
        hardwareId: "none",
      },
    ],
  },
  trim_package: {
    name: names.trim_package,
    version: 1,
    units: "mm",
    millworkFamily: "trim",
    millworkAssemblyType: "trim_package",
    totalWidth: 3200,
    height: 160,
    depth: 90,
    boardThickness: 18,
    backPanelThickness: 6,
    toeKickHeight: 0,
    revealGap: 3,
    modules: [
      {
        width: 3200,
        type: "wall",
        millworkComponentType: "trim_run",
        frontType: "open",
        doorStyle: "flat_slab",
        doorCount: 0,
        drawerCount: 0,
        shelfCount: 0,
        trimMemberCount: 4,
        trimProfileWidth: 160,
        trimProfileDepth: 24,
        trimOrientation: "x",
        trimPlacement: "baseboard",
        trimSetoutHeight: 0,
        materialId: "painted_shaker_white",
        frontMaterialId: "painted_shaker_white",
        hardwareId: "none",
      },
    ],
  },
};
