#!/bin/bash
# Quick Start Guide for Phase 5 Implementation

echo "🚀 Phase 5 - Quality Gates & Error Handling Implementation"
echo "==========================================================="
echo ""

echo "📦 Step 1: Install Dependencies"
echo "Run: npm install"
echo "Then: npx playwright install"
echo ""

echo "⚙️  Step 2: Configure Environment"
echo "1. Copy .env.local from .env.example (if exists)"
echo "2. Add NEXT_PUBLIC_SENTRY_DSN from sentry.io"
echo "3. Keep DATABASE_URL pointing to your dev DB"
echo "4. Set NEXTAUTH_SECRET and NEXTAUTH_URL"
echo ""

echo "🏷️  Step 3: Add Test IDs to UI"
echo "See TEST_IDS.md for required data-testid attributes"
echo "Key components to update:"
echo "  - Canvas: data-testid=\"scene-canvas\""
echo "  - Buttons: Save, Share, Present, etc."
echo "  - Modals: Cart, Room Switcher, etc."
echo "  - Items: data-testid=\"item-in-scene\""
echo ""

echo "🔗 Step 4: Integrate into Components"
echo "In your main layout/page:"
echo ""
echo "1. Wrap canvas with CanvasErrorBoundary:"
echo "   <CanvasErrorBoundary>"
echo "     <Canvas>...</Canvas>"
echo "   </CanvasErrorBoundary>"
echo ""
echo "2. Add FPSMeter for dev:"
echo "   {process.env.NODE_ENV === 'development' && <FPSMeter />}"
echo ""
echo "3. Set Sentry context on state changes:"
echo "   useEffect(() => {"
echo "     setSentryContext({ designId, mode, roomId, plan, isGuest });"
echo "   }, [designId, mode, roomId, plan, isGuest]);"
echo ""

echo "🧪 Step 5: Run Tests"
echo "npm run test:e2e           # Run all tests"
echo "npm run test:e2e:ui        # Interactive UI"
echo "npm run test:e2e:headed    # See browser"
echo ""

echo "✅ Step 6: Setup GitHub Actions"
echo "1. Go to GitHub repo → Settings → Secrets and variables → Actions"
echo "2. Add:"
echo "   - SENTRY_DSN"
echo "   - DATABASE_URL"
echo "   - NEXTAUTH_SECRET"
echo "3. Push code → Actions runs automatically"
echo ""

echo "📊 Documentation"
echo "=================="
echo "TESTING_QUALITY_GATES.md  - Overview of all quality gates"
echo "TEST_IDS.md              - Required data-testid attributes"
echo "ENV_SETUP.md             - Environment configuration"
echo "PHASE5_CHECKLIST.md      - Implementation checklist"
echo ""

echo "🎯 What's Included"
echo "=================="
echo "✅ 5 Core E2E Test Flows (11 total tests)"
echo "   - Onboarding flow"
echo "   - Editor correctness (collision, wall snap, undo/redo)"
echo "   - Save + reload persistence"
echo "   - Share link read-only"
echo "   - Buy flow (Shopify + affiliate)"
echo ""
echo "✅ Error Reporting (Sentry)"
echo "   - Client & server integration"
echo "   - R3F error boundary"
echo "   - Context: designId, mode, roomId, plan, isGuest"
echo ""
echo "✅ Performance Monitoring"
echo "   - Dev: FPS meter (toggle with F)"
echo "   - Prod: Silent tracking (bad signals only)"
echo ""
echo "✅ CI/CD Pipeline"
echo "   - Typecheck → Lint → Build → E2E → Merge Gate"
echo "   - Blocks merge on failures"
echo ""

echo "🔥 Next Immediate Actions"
echo "=========================="
echo "1. npm install"
echo "2. Edit TEST_IDS.md with your component selectors"
echo "3. Add data-testid attributes to UI"
echo "4. Set NEXT_PUBLIC_SENTRY_DSN in .env.local"
echo "5. Wrap canvas in CanvasErrorBoundary"
echo "6. Run npm run test:e2e"
echo ""

echo "✨ Done! Your quality gates are ready to use."
echo "Start implementing by following the PHASE5_CHECKLIST.md file."
echo ""
