import fs from "node:fs";
import { test, expect } from "../fixtures";
import { openDetailedProStudio, placeCabinetRun } from "./helpers";

export function registerExportTests() {
  test.describe("Custom Millwork Studio export", () => {
    test.setTimeout(600000);

    test("Pro designer can export a cabinet-run fabrication package", async ({ page }) => {
      await openDetailedProStudio(page);
      await page.getByTestId("cabinet-preset-cabinet_run").click();
      await expect(page.getByTestId("cabinet-module-3")).toBeVisible();
      await expect(page.getByTestId("cabinet-module-move-left")).toBeDisabled();
      await page.getByTestId("cabinet-module-3").click();
      await expect(page.getByTestId("cabinet-module-move-right")).toBeDisabled();
      await page.getByTestId("cabinet-module-move-left").click();
      await expect(page.getByTestId("cabinet-module-2")).toHaveAttribute("data-module-id", "module-3");
      await expect(page.getByTestId("cabinet-bom")).toHaveAttribute("data-bom-count", /\d+/);
      await expect(page.getByTestId("cabinet-assembly-profile")).toHaveAttribute("data-assembly-profile-schema", "custom_millwork.assembly_profile.v1");
      await expect(page.getByTestId("cabinet-assembly-profile")).toHaveAttribute("data-assembly-profile-label", "Cabinet run");
      await expect(page.getByTestId("cabinet-assembly-profile")).toHaveAttribute("data-assembly-profile-phase", "mvp");
      await expect(page.getByTestId("cabinet-assembly-profile")).toHaveAttribute("data-assembly-profile-placement-kind", "built_in_wall");
      await expect(page.getByTestId("cabinet-assembly-profile")).toHaveAttribute("data-assembly-profile-complexity", "moderate");
      await expect(page.getByTestId("cabinet-quote-summary")).toHaveAttribute("data-quote-total", /\d+/);
      await expect(page.getByTestId("cabinet-quote-summary")).toHaveAttribute("data-quote-line-count", /\d+/);
      await expect(page.getByTestId("cabinet-supplier-readiness")).toHaveAttribute("data-supplier-readiness-status", "ready_for_fabricator_review");
      await expect(page.getByTestId("cabinet-supplier-readiness")).toHaveAttribute("data-supplier-sku-mapping-count", "10");
      await expect(page.getByTestId("cabinet-supplier-readiness")).toHaveAttribute("data-mapped-sku-count", "7");
      await expect(page.getByTestId("cabinet-supplier-readiness")).toHaveAttribute("data-missing-sku-count", "0");
      await expect(page.getByTestId("cabinet-supplier-readiness")).toHaveAttribute("data-custom-quote-required-count", "3");
      await expect(page.getByTestId("cabinet-supplier-sku-row")).toHaveCount(10);
      await expect(page.getByTestId("cabinet-fabrication-release-readiness")).toHaveAttribute("data-fabrication-release-status", "needs_review");
      await expect(page.getByTestId("cabinet-fabrication-release-readiness")).toHaveAttribute("data-fabrication-release-required-count", "7");
      await expect(page.getByTestId("cabinet-fabrication-release-readiness")).toHaveAttribute("data-fabrication-release-blocker-count", "0");
      await expect(page.getByTestId("cabinet-fabrication-release-readiness")).toHaveAttribute("data-fabrication-release-gate-count", "5");
      await expect(page.getByTestId("cabinet-fabrication-release-readiness")).toHaveAttribute("data-installation-gate-count", "1");
      await expect(page.getByTestId("cabinet-dimension-schedule")).toHaveAttribute("data-dimension-schedule-count", "4");
      await expect(page.getByTestId("cabinet-drawing-view-schedule")).toHaveAttribute("data-drawing-view-schedule-count", "9");
      await expect(page.getByTestId("cabinet-material-schedule")).toHaveAttribute("data-material-schedule-count", "4");
      await expect(page.getByTestId("cabinet-hardware-schedule")).toHaveAttribute("data-hardware-schedule-count", "3");
      await expect(page.getByTestId("cabinet-edge-banding-schedule")).toHaveAttribute("data-edge-banding-schedule-count", "4");
      await expect(page.getByTestId("cabinet-edge-banding-schedule")).toHaveAttribute("data-edge-banding-total-m", "28.23");
      await expect(page.getByTestId("cabinet-edge-banding-row")).toHaveCount(4);
      await expect(page.getByTestId("cabinet-cut-list")).toHaveAttribute("data-cut-list-count", "30");
      await expect(page.getByTestId("cabinet-installer-notes")).toHaveAttribute("data-installer-note-count", /\d+/);
      await expect(page.getByTestId("cabinet-release-checklist")).toHaveAttribute("data-release-checklist-count", "7");
      await expect(page.getByTestId("cabinet-release-checklist")).toHaveAttribute("data-release-blocker-count", "0");

      await page.getByTestId("cabinet-output-tab-outputs").click();
      const sourceDownloadPromise = page.waitForEvent("download");
      await page.getByTestId("cabinet-download-source-definition").click();
      const sourceDownload = await sourceDownloadPromise;
      const sourceDownloadPath = await sourceDownload.path();
      expect(sourceDownloadPath).toBeTruthy();
      expect(sourceDownload.suggestedFilename()).toMatch(/source-definition\.json$/);
      const sourceJson = JSON.parse(fs.readFileSync(sourceDownloadPath!, "utf8"));
      expect(sourceJson.schema).toBe("custom_millwork.source_definition.v1");
      expect(sourceJson.sourceType).toBe("cabinet_definition");
      expect(sourceJson.cabinetDefinition.modules).toHaveLength(3);
      expect(sourceJson.cabinetDefinition.modules.map((module: { id: string }) => module.id)).toEqual([
        "module-1",
        "module-3",
        "module-2",
      ]);
      expect(sourceJson.millworkDefinition.schema).toBe("custom_millwork.definition.v1");
      expect(sourceJson.millworkDefinition.assemblyProfile.schema).toBe("custom_millwork.assembly_profile.v1");
      expect(sourceJson.millworkDefinition.assemblyProfile.assemblyType).toBe("cabinet_run");
      expect(sourceJson.millworkDefinition.assemblyProfile.projectPhase).toBe("mvp");
      expect(sourceJson.millworkDefinition.sourceDefinition.id).toBe(sourceJson.cabinetDefinition.id);
      expect(sourceJson.sourceDefinitionFingerprint).toMatch(/^cabdef-v1-/);
      expect(sourceJson.notes.some((note: string) => note.includes("source of truth"))).toBe(true);

      await expect(page.getByTestId("cabinet-import-source-definition")).toBeVisible();
      await page.getByTestId("cabinet-preset-base").click();
      await expect(page.getByTestId("cabinet-module-3")).toHaveCount(0);
      await page.getByTestId("cabinet-import-source-definition-input").setInputFiles({
        name: sourceDownload.suggestedFilename(),
        mimeType: "application/json",
        buffer: fs.readFileSync(sourceDownloadPath!),
      });
      await expect(page.getByTestId("cabinet-action-success")).toContainText(/Source definition imported/i);
      await expect(page.getByTestId("cabinet-module-3")).toBeVisible();
      await expect(page.getByTestId("cabinet-dimension-schedule")).toHaveAttribute("data-dimension-schedule-count", "4");
      await expect(page.getByTestId("cabinet-edge-banding-schedule")).toHaveAttribute("data-edge-banding-schedule-count", "4");
      await expect(page.getByTestId("cabinet-cut-list")).toHaveAttribute("data-cut-list-count", "30");

      const docsDownloadPromise = page.waitForEvent("download");
      await page.getByTestId("cabinet-download-documentation").click();
      const docsDownload = await docsDownloadPromise;
      const docsDownloadPath = await docsDownload.path();
      expect(docsDownloadPath).toBeTruthy();
      expect(docsDownload.suggestedFilename()).toMatch(/documentation\.csv$/);
      const docsText = fs.readFileSync(docsDownloadPath!, "utf8");
      expect(docsText).toContain("Custom Millwork Documentation");
      expect(docsText).toContain("Assembly Profile");
      expect(docsText).toContain("Cabinet run");
      expect(docsText).toContain("Preliminary Quote Summary");
      expect(docsText).toContain("Quote Line Items");
      expect(docsText).toContain("Edge Banding Schedule");
      expect(docsText).toContain("Dimension Schedule");
      expect(docsText).toContain("Drawing Views");
      expect(docsText).toContain("BOM");
      expect(docsText).toContain("Material Schedule");
      expect(docsText).toContain("Hardware Schedule");
      expect(docsText).toContain("Supplier Readiness");
      expect(docsText).toContain("Supplier SKU Mappings");
      expect(docsText).toContain("Cut List");
      expect(docsText).toContain("Installer Notes");
      expect(docsText).toContain("Release Checklist");

      const shopDrawingDownloadPromise = page.waitForEvent("download");
      await page.getByTestId("cabinet-download-shop-drawing-svg").click();
      const shopDrawingDownload = await shopDrawingDownloadPromise;
      const shopDrawingDownloadPath = await shopDrawingDownload.path();
      expect(shopDrawingDownloadPath).toBeTruthy();
      expect(shopDrawingDownload.suggestedFilename()).toMatch(/shop-drawing\.svg$/);
      const shopDrawingSvg = fs.readFileSync(shopDrawingDownloadPath!, "utf8");
      expect(shopDrawingSvg).toContain("<svg");
      expect(shopDrawingSvg).toContain("A-601 Overall Front Elevation");
      expect(shopDrawingSvg).toContain("A-602 Typical Side Section");
      expect(shopDrawingSvg).toContain("A-603 Plan Footprint");

      const dxfDownloadPromise = page.waitForEvent("download");
      await page.getByTestId("cabinet-download-fabrication-dxf").click();
      const dxfDownload = await dxfDownloadPromise;
      const dxfDownloadPath = await dxfDownload.path();
      expect(dxfDownloadPath).toBeTruthy();
      expect(dxfDownload.suggestedFilename()).toMatch(/cut-layout\.dxf$/);
      const dxfText = fs.readFileSync(dxfDownloadPath!, "utf8");
      expect(dxfText).toContain("$INSUNITS");
      expect(dxfText).toContain("SECTION\n2\nENTITIES");
      expect(dxfText).toContain("CUT");
      expect(dxfText).toContain("module-1:left_side_panel:0");

      const rfqDownloadPromise = page.waitForEvent("download");
      await page.getByTestId("cabinet-download-fabrication-rfq").click();
      const rfqDownload = await rfqDownloadPromise;
      const rfqDownloadPath = await rfqDownload.path();
      expect(rfqDownloadPath).toBeTruthy();
      expect(rfqDownload.suggestedFilename()).toMatch(/rfq\.json$/);
      const rfqJson = JSON.parse(fs.readFileSync(rfqDownloadPath!, "utf8"));
      expect(rfqJson.schema).toBe("custom_millwork.rfq.v1");
      expect(rfqJson.sourceDefinitionFingerprint).toBe(sourceJson.sourceDefinitionFingerprint);
      expect(rfqJson.readiness.status).toBe("ready_for_fabricator_review");
      expect(rfqJson.readiness.mappedSkuCount).toBeGreaterThan(0);
      expect(rfqJson.readiness.customQuoteRequiredCount).toBeGreaterThan(0);
      expect(rfqJson.readiness.releaseChecklistCount).toBe(7);
      expect(rfqJson.readiness.releaseBlockerCount).toBe(0);
      expect(rfqJson.supplierSkuMappings.some((item: { sourceType: string; status: string }) => item.sourceType === "material" && item.status === "mapped")).toBe(true);
      expect(rfqJson.supplierSkuMappings.some((item: { sourceType: string; status: string }) => item.sourceType === "fabrication_service" && item.status === "custom_quote_required")).toBe(true);
      expect(rfqJson.artifacts.some((item: { type: string; fileName: string }) => item.type === "source_definition" && item.fileName.endsWith("source-definition.json"))).toBe(true);
      expect(rfqJson.artifacts.some((item: { type: string; fileName: string }) => item.type === "fabrication_dxf" && item.fileName.endsWith("cut-layout.dxf"))).toBe(true);
      expect(rfqJson.artifacts.some((item: { type: string; fileName: string }) => item.type === "shop_drawing_svg" && item.fileName.endsWith("shop-drawing.svg"))).toBe(true);
      expect(rfqJson.documentation.cutList).toHaveLength(30);
      expect(rfqJson.documentation.edgeBandingSchedule).toHaveLength(4);
      expect(rfqJson.documentation.releaseChecklist).toHaveLength(7);

      const packageDownloadPromise = page.waitForEvent("download");
      await page.getByTestId("cabinet-download-package-json").click();
      const packageDownload = await packageDownloadPromise;
      const packageDownloadPath = await packageDownload.path();
      expect(packageDownloadPath).toBeTruthy();
      expect(packageDownload.suggestedFilename()).toMatch(/package\.json$/);
      const packageJson = JSON.parse(fs.readFileSync(packageDownloadPath!, "utf8"));
      expect(packageJson.schema).toBe("custom_millwork.package.v1");
      expect(packageJson.sourceType).toBe("cabinet_definition");
      expect(packageJson.sourceDefinitionFingerprint).toBe(sourceJson.sourceDefinitionFingerprint);
      expect(packageJson.cabinetDefinition.modules).toHaveLength(3);
      expect(packageJson.millworkDefinition.schema).toBe("custom_millwork.definition.v1");
      expect(packageJson.millworkDefinition.assemblyProfile.assemblyType).toBe("cabinet_run");
      expect(packageJson.millworkDefinition.sourceDefinition.id).toBe(packageJson.cabinetDefinition.id);
      expect(packageJson.documentation.assemblyProfile.schema).toBe("custom_millwork.assembly_profile.v1");
      expect(packageJson.documentation.assemblyProfile.placementKind).toBe("built_in_wall");
      expect(packageJson.documentation.drawingViewSchedule).toHaveLength(9);
      expect(packageJson.documentation.drawingViewSchedule.some((item: { viewType: string }) => item.viewType === "front_elevation")).toBe(true);
      expect(packageJson.documentation.drawingViewSchedule.some((item: { viewType: string }) => item.viewType === "side_section")).toBe(true);
      expect(packageJson.documentation.drawingViewSchedule.some((item: { viewType: string }) => item.viewType === "plan_footprint")).toBe(true);
      expect(packageJson.documentation.edgeBandingSchedule).toHaveLength(4);
      expect(packageJson.documentation.edgeBandingSchedule.reduce((sum: number, item: { totalLengthM: number }) => sum + item.totalLengthM, 0)).toBeCloseTo(28.23, 2);
      expect(packageJson.documentation.supplierSkuMappings).toHaveLength(10);
      expect(packageJson.documentation.supplierReadiness.status).toBe("ready_for_fabricator_review");
      expect(packageJson.documentation.supplierReadiness.mappedSkuCount).toBe(7);
      expect(packageJson.documentation.supplierReadiness.customQuoteRequiredCount).toBe(3);
      expect(packageJson.documentation.fabricationReleaseReadiness.status).toBe("needs_review");
      expect(packageJson.documentation.fabricationReleaseReadiness.requiredGateCount).toBe(7);
      expect(packageJson.quoteRequest.schema).toBe("custom_millwork.rfq.v1");
      expect(packageJson.quoteRequest.artifacts.some((item: { type: string }) => item.type === "source_definition")).toBe(true);
      expect(packageJson.quoteRequest.artifacts.some((item: { type: string }) => item.type === "fabrication_dxf")).toBe(true);
      expect(packageJson.quoteRequest.artifacts.some((item: { type: string }) => item.type === "shop_drawing_svg")).toBe(true);
      expect(packageJson.quoteRequest.documentation.releaseChecklist).toHaveLength(7);
      expect(packageJson.documentation.quoteSummary.estimatedTotal).toBeGreaterThan(0);

      const downloadPromise = page.waitForEvent("download");
      await page.getByTestId("cabinet-download-glb").click();
      const download = await downloadPromise;
      const downloadPath = await download.path();
      expect(downloadPath).toBeTruthy();
      const bytes = fs.readFileSync(downloadPath!);
      expect(bytes.length).toBeGreaterThan(1000);
      expect(bytes.subarray(0, 4).toString("utf8")).toBe("glTF");
    });

    test("Pro designer can export placed, installer, and field-finish packages", async ({
      page,
    }) => {
      const { sourceJson, instanceId } = await placeCabinetRun(page);
      const placedPackageDownloadPromise = page.waitForEvent("download");
      await page.getByTestId("selected-cabinet-download-placed-package").click();
      const placedPackageDownload = await placedPackageDownloadPromise;
      const placedPackagePath = await placedPackageDownload.path();
      expect(placedPackagePath).toBeTruthy();
      expect(placedPackageDownload.suggestedFilename()).toMatch(/placed-package\.json$/);
      const placedPackageJson = JSON.parse(fs.readFileSync(placedPackagePath!, "utf8"));
      expect(placedPackageJson.schema).toBe("custom_millwork.placed_asset_package.v1");
      expect(placedPackageJson.sourceType).toBe("placed_parametric_cabinet");
      expect(placedPackageJson.sourceDefinitionFingerprint).toBe(sourceJson.sourceDefinitionFingerprint);
      expect(placedPackageJson.assetManifest.schema).toBe("custom_millwork.asset_manifest.v1");
      expect(placedPackageJson.assetManifest.assetId).toBe(instanceId);
      expect(placedPackageJson.assetManifest.sourceDefinitionVersion).toBe(1);
      expect(placedPackageJson.assetManifest.generatedOutput.kind).toBe("glb");
      expect(placedPackageJson.assetManifest.generatedOutput.durable).toBe(false);
      expect(placedPackageJson.placedAsset.id).toBe(instanceId);
      expect(placedPackageJson.placedAsset.assetType).toBe("parametric_cabinet");
      expect(placedPackageJson.placedAsset.assetManifest.schema).toBe("custom_millwork.asset_manifest.v1");
      expect(placedPackageJson.placedAsset.roomId).toBeTruthy();
      expect(placedPackageJson.placedAsset.transform.position).toHaveLength(3);
      expect(placedPackageJson.placedAsset.transform.rotation).toHaveLength(3);
      expect(placedPackageJson.placedAsset.glbAssetUrl).toContain("blob:");
      expect(placedPackageJson.cabinetDefinition.id).toBe(placedPackageJson.placedAsset.cabinetDefinition.id);
      expect(placedPackageJson.millworkDefinition.sourceDefinition.id).toBe(placedPackageJson.cabinetDefinition.id);
      expect(placedPackageJson.documentation.supplierSkuMappings).toHaveLength(10);
      expect(placedPackageJson.documentation.edgeBandingSchedule).toHaveLength(4);
      expect(placedPackageJson.documentation.supplierReadiness.status).toBe("ready_for_fabricator_review");
      expect(placedPackageJson.documentation.fabricationReleaseReadiness.status).toBe("needs_review");
      expect(placedPackageJson.documentation.fabricationReleaseReadiness.requiredGateCount).toBe(7);
      expect(placedPackageJson.quoteRequest.schema).toBe("custom_millwork.rfq.v1");
      expect(placedPackageJson.quoteRequest.sourceDefinitionFingerprint).toBe(sourceJson.sourceDefinitionFingerprint);
      expect(placedPackageJson.installerWorkOrder.schema).toBe("custom_millwork.installer_work_order.v1");
      expect(placedPackageJson.installerWorkOrder.sourceDefinitionFingerprint).toBe(sourceJson.sourceDefinitionFingerprint);
      expect(placedPackageJson.installerWorkOrder.placedAsset.id).toBe(instanceId);
      expect(placedPackageJson.installerWorkOrder.siteTransform.position).toHaveLength(3);
      const installerWorkOrderDownloadPromise = page.waitForEvent("download");
      await page.getByTestId("selected-cabinet-download-installer-work-order").click();
      const installerWorkOrderDownload = await installerWorkOrderDownloadPromise;
      const installerWorkOrderPath = await installerWorkOrderDownload.path();
      expect(installerWorkOrderPath).toBeTruthy();
      expect(installerWorkOrderDownload.suggestedFilename()).toMatch(/installer-work-order\.json$/);
      const installerWorkOrderJson = JSON.parse(fs.readFileSync(installerWorkOrderPath!, "utf8"));
      expect(installerWorkOrderJson.schema).toBe("custom_millwork.installer_work_order.v1");
      expect(installerWorkOrderJson.sourceType).toBe("placed_parametric_cabinet");
      expect(installerWorkOrderJson.sourceDefinitionFingerprint).toBe(sourceJson.sourceDefinitionFingerprint);
      expect(installerWorkOrderJson.placedAsset.id).toBe(instanceId);
      expect(installerWorkOrderJson.roomName).toBeTruthy();
      expect(installerWorkOrderJson.siteTransform.position).toEqual(placedPackageJson.placedAsset.transform.position);
      expect(installerWorkOrderJson.siteTransform.rotation).toEqual(placedPackageJson.placedAsset.transform.rotation);
      expect(installerWorkOrderJson.installationScope.releaseStatus).toBe("needs_review");
      expect(installerWorkOrderJson.documentation.installerNotes.length).toBeGreaterThan(0);
      expect(installerWorkOrderJson.artifacts.some((item: { type: string }) => item.type === "installer_work_order_json")).toBe(true);
      expect(installerWorkOrderJson.artifacts.some((item: { type: string }) => item.type === "package_json")).toBe(true);
      const projectFieldVerificationDownloadPromise = page.waitForEvent("download");
      await page.getByTestId("selected-cabinet-download-project-field-verification").click();
      const projectFieldVerificationDownload = await projectFieldVerificationDownloadPromise;
      const projectFieldVerificationPath = await projectFieldVerificationDownload.path();
      expect(projectFieldVerificationPath).toBeTruthy();
      expect(projectFieldVerificationDownload.suggestedFilename()).toMatch(/field-verification\.json$/);
      const projectFieldVerificationJson = JSON.parse(fs.readFileSync(projectFieldVerificationPath!, "utf8"));
      expect(projectFieldVerificationJson.schema).toBe("custom_millwork.project_field_verification.v1");
      expect(projectFieldVerificationJson.verificationStatus).toBe("field_verification_required");
      expect(projectFieldVerificationJson.canReleaseWithoutFieldVerification).toBe(false);
      expect(projectFieldVerificationJson.fabricationReleasePackage.schema).toBe("custom_millwork.project_fabrication_release.v1");
      expect(projectFieldVerificationJson.installationPlanPackage.schema).toBe("custom_millwork.project_installation_plan.v1");
      expect(projectFieldVerificationJson.totals.assetCount).toBe(1);
      expect(projectFieldVerificationJson.totals.roomCount).toBe(1);
      expect(projectFieldVerificationJson.totals.requiredCheckCount).toBeGreaterThan(0);
      expect(projectFieldVerificationJson.totals.fieldVerifyNoteCount).toBeGreaterThan(0);
      expect(projectFieldVerificationJson.assets[0].id).toBe(instanceId);
      expect(projectFieldVerificationJson.assets[0].siteTransform.position).toEqual(placedPackageJson.placedAsset.transform.position);
      expect(projectFieldVerificationJson.rooms[0].assetIds).toContain(instanceId);
      expect(projectFieldVerificationJson.checklist.some((item: { scope: string }) => item.scope === "site_measurement")).toBe(true);
      expect(projectFieldVerificationJson.checklist.some((item: { scope: string }) => item.scope === "placement")).toBe(true);
      expect(projectFieldVerificationJson.fieldVerificationPolicy.requiresHumanVerification).toBe(true);
      expect(projectFieldVerificationJson.artifacts.some((item: { type: string }) => item.type === "project_field_verification_json")).toBe(true);
      expect(projectFieldVerificationJson.artifacts.some((item: { type: string }) => item.type === "project_finish_schedule_json")).toBe(true);
      expect(projectFieldVerificationJson.artifacts.some((item: { type: string }) => item.type === "project_installation_plan_json")).toBe(true);
      expect(projectFieldVerificationJson.artifacts.some((item: { type: string }) => item.type === "installer_work_order_json")).toBe(true);
      const projectFinishScheduleDownloadPromise = page.waitForEvent("download");
      await page.getByTestId("selected-cabinet-download-project-finish-schedule").click();
      const projectFinishScheduleDownload = await projectFinishScheduleDownloadPromise;
      const projectFinishSchedulePath = await projectFinishScheduleDownload.path();
      expect(projectFinishSchedulePath).toBeTruthy();
      expect(projectFinishScheduleDownload.suggestedFilename()).toMatch(/finish-schedule\.json$/);
      const projectFinishScheduleJson = JSON.parse(fs.readFileSync(projectFinishSchedulePath!, "utf8"));
      expect(projectFinishScheduleJson.schema).toBe("custom_millwork.project_finish_schedule.v1");
      expect(projectFinishScheduleJson.schedule.schema).toBe("custom_millwork.project_schedule.v1");
      expect(projectFinishScheduleJson.procurementPackage.schema).toBe("custom_millwork.project_procurement.v1");
      expect(projectFinishScheduleJson.totals.assetCount).toBe(1);
      expect(projectFinishScheduleJson.totals.roomCount).toBe(1);
      expect(projectFinishScheduleJson.totals.materialCount).toBeGreaterThan(0);
      expect(projectFinishScheduleJson.totals.hardwareCount).toBeGreaterThan(0);
      expect(projectFinishScheduleJson.totals.edgeBandingCount).toBe(4);
      expect(projectFinishScheduleJson.totals.edgeBandingTotalM).toBe(28.23);
      expect(projectFinishScheduleJson.totals.mappedSkuCount).toBe(7);
      expect(projectFinishScheduleJson.totals.customQuoteRequiredCount).toBe(3);
      expect(projectFinishScheduleJson.materials.every((item: { assetIds: string[] }) => item.assetIds.includes(instanceId!))).toBe(true);
      expect(projectFinishScheduleJson.hardware.every((item: { assetIds: string[] }) => item.assetIds.includes(instanceId!))).toBe(true);
      expect(projectFinishScheduleJson.edgeBanding.every((item: { assetIds: string[] }) => item.assetIds.includes(instanceId!))).toBe(true);
      expect(projectFinishScheduleJson.materials.some((item: { supplierStatus?: string }) => item.supplierStatus === "mapped")).toBe(true);
      expect(projectFinishScheduleJson.finishReviewPolicy.requiresDesignerApproval).toBe(true);
      expect(projectFinishScheduleJson.finishReviewPolicy.requiresClientApproval).toBe(true);
      expect(projectFinishScheduleJson.finishReviewPolicy.requiresSupplierConfirmation).toBe(true);
      expect(projectFinishScheduleJson.assets[0].id).toBe(instanceId);
      expect(projectFinishScheduleJson.artifacts.some((item: { type: string }) => item.type === "project_finish_schedule_json")).toBe(true);
      expect(projectFinishScheduleJson.artifacts.some((item: { type: string }) => item.type === "project_procurement_json")).toBe(true);
      expect(projectFinishScheduleJson.artifacts.some((item: { type: string }) => item.type === "project_rfq_json")).toBe(true);
    });

    test("Pro designer can export project commercial and release-readiness packages", async ({
      page,
    }) => {
      const { sourceJson, instanceId } = await placeCabinetRun(page);
      const projectScheduleDownloadPromise = page.waitForEvent("download");
      await page.getByTestId("selected-cabinet-download-project-schedule").click();
      const projectScheduleDownload = await projectScheduleDownloadPromise;
      const projectSchedulePath = await projectScheduleDownload.path();
      expect(projectSchedulePath).toBeTruthy();
      expect(projectScheduleDownload.suggestedFilename()).toMatch(/millwork-schedule\.json$/);
      const projectScheduleJson = JSON.parse(fs.readFileSync(projectSchedulePath!, "utf8"));
      expect(projectScheduleJson.schema).toBe("custom_millwork.project_schedule.v1");
      expect(projectScheduleJson.totals.assetCount).toBe(1);
      expect(projectScheduleJson.totals.roomCount).toBe(1);
      expect(projectScheduleJson.totals.edgeBandingTotalM).toBe(28.23);
      expect(projectScheduleJson.assets[0].id).toBe(instanceId);
      expect(projectScheduleJson.assets[0].sourceDefinitionFingerprint).toBe(sourceJson.sourceDefinitionFingerprint);
      expect(projectScheduleJson.assetManifests[0].schema).toBe("custom_millwork.asset_manifest.v1");
      expect(projectScheduleJson.placedAssets[0].cabinetDefinition.id).toBe(projectScheduleJson.assets[0].sourceDefinitionId);
      const projectScheduleCsvDownloadPromise = page.waitForEvent("download");
      await page.getByTestId("selected-cabinet-download-project-schedule-csv").click();
      const projectScheduleCsvDownload = await projectScheduleCsvDownloadPromise;
      const projectScheduleCsvPath = await projectScheduleCsvDownload.path();
      expect(projectScheduleCsvPath).toBeTruthy();
      expect(projectScheduleCsvDownload.suggestedFilename()).toMatch(/millwork-schedule\.csv$/);
      const projectScheduleCsv = fs.readFileSync(projectScheduleCsvPath!, "utf8");
      expect(projectScheduleCsv).toContain("Custom Millwork Project Schedule");
      expect(projectScheduleCsv).toContain("Project Totals");
      expect(projectScheduleCsv).toContain("Rooms");
      expect(projectScheduleCsv).toContain("Placed Millwork Assets");
      expect(projectScheduleCsv).toContain(instanceId!);
      expect(projectScheduleCsv).toContain("28.23");
      const projectScopeDownloadPromise = page.waitForEvent("download");
      await page.getByTestId("selected-cabinet-download-project-scope").click();
      const projectScopeDownload = await projectScopeDownloadPromise;
      const projectScopePath = await projectScopeDownload.path();
      expect(projectScopePath).toBeTruthy();
      expect(projectScopeDownload.suggestedFilename()).toMatch(/scope\.json$/);
      const projectScopeJson = JSON.parse(fs.readFileSync(projectScopePath!, "utf8"));
      expect(projectScopeJson.schema).toBe("custom_millwork.project_scope.v1");
      expect(projectScopeJson.schedule.schema).toBe("custom_millwork.project_schedule.v1");
      expect(projectScopeJson.totals.assetCount).toBe(1);
      expect(projectScopeJson.totals.familyCount).toBe(1);
      expect(projectScopeJson.totals.assemblyTypeCount).toBe(1);
      expect(projectScopeJson.totals.sourceDefinitionFingerprintCount).toBe(1);
      expect(projectScopeJson.families.some((item: { family: string; sourceDefinitionFingerprints: string[] }) => item.family === "cabinetry" && item.sourceDefinitionFingerprints.includes(sourceJson.sourceDefinitionFingerprint))).toBe(true);
      expect(projectScopeJson.assemblies.some((item: { assemblyType: string; sourceDefinitionFingerprints: string[] }) => item.assemblyType === "cabinet_run" && item.sourceDefinitionFingerprints.includes(sourceJson.sourceDefinitionFingerprint))).toBe(true);
      expect(projectScopeJson.coverage.some((item: { scopeId: string; status: string }) => item.scopeId === "mvp" && item.status === "partially_represented")).toBe(true);
      expect(projectScopeJson.coverage.some((item: { scopeId: string; status: string }) => item.scopeId === "phase_5" && item.status === "represented")).toBe(true);
      expect(projectScopeJson.coverage.some((item: { scopeId: string; status: string }) => item.scopeId === "phase_6" && item.status === "represented")).toBe(true);
      expect(projectScopeJson.artifacts.some((item: { type: string }) => item.type === "project_scope_json")).toBe(true);
      expect(projectScopeJson.artifacts.some((item: { type: string }) => item.type === "project_schedule_json")).toBe(true);
      expect(projectScopeJson.artifacts.some((item: { type: string }) => item.type === "project_handoff_package_json")).toBe(true);
      expect(projectScopeJson.artifacts.some((item: { type: string }) => item.type === "package_json")).toBe(true);
      const projectProcurementDownloadPromise = page.waitForEvent("download");
      await page.getByTestId("selected-cabinet-download-project-procurement").click();
      const projectProcurementDownload = await projectProcurementDownloadPromise;
      const projectProcurementPath = await projectProcurementDownload.path();
      expect(projectProcurementPath).toBeTruthy();
      expect(projectProcurementDownload.suggestedFilename()).toMatch(/procurement\.json$/);
      const projectProcurementJson = JSON.parse(fs.readFileSync(projectProcurementPath!, "utf8"));
      expect(projectProcurementJson.schema).toBe("custom_millwork.project_procurement.v1");
      expect(projectProcurementJson.schedule.schema).toBe("custom_millwork.project_schedule.v1");
      expect(projectProcurementJson.checkoutPolicy.includeInCheckout).toBe(false);
      expect(projectProcurementJson.totals.lineCount).toBe(10);
      expect(projectProcurementJson.totals.mappedSkuCount).toBe(7);
      expect(projectProcurementJson.totals.customQuoteRequiredCount).toBe(3);
      expect(projectProcurementJson.totals.estimatedTotal).toBeGreaterThan(0);
      expect(projectProcurementJson.lineItems.some((item: { sourceType: string; status: string }) => item.sourceType === "material" && item.status === "mapped")).toBe(true);
      expect(projectProcurementJson.lineItems.some((item: { sourceType: string; status: string }) => item.sourceType === "fabrication_service" && item.status === "custom_quote_required")).toBe(true);
      expect(projectProcurementJson.lineItems.every((item: { assetIds: string[] }) => item.assetIds.includes(instanceId!))).toBe(true);
      expect(projectProcurementJson.artifacts.some((item: { type: string }) => item.type === "project_procurement_json")).toBe(true);
      expect(projectProcurementJson.artifacts.some((item: { type: string }) => item.type === "project_finish_schedule_json")).toBe(true);
      const projectQuoteDownloadPromise = page.waitForEvent("download");
      await page.getByTestId("selected-cabinet-download-project-quote").click();
      const projectQuoteDownload = await projectQuoteDownloadPromise;
      const projectQuotePath = await projectQuoteDownload.path();
      expect(projectQuotePath).toBeTruthy();
      expect(projectQuoteDownload.suggestedFilename()).toMatch(/project-quote\.json$/);
      const projectQuoteJson = JSON.parse(fs.readFileSync(projectQuotePath!, "utf8"));
      expect(projectQuoteJson.schema).toBe("custom_millwork.project_quote.v1");
      expect(projectQuoteJson.quoteStatus).toBe("needs_supplier_quote");
      expect(projectQuoteJson.schedule.schema).toBe("custom_millwork.project_schedule.v1");
      expect(projectQuoteJson.procurementPackage.schema).toBe("custom_millwork.project_procurement.v1");
      expect(projectQuoteJson.approvalPackage.schema).toBe("custom_millwork.project_approval_package.v1");
      expect(projectQuoteJson.fabricationReleasePackage.schema).toBe("custom_millwork.project_fabrication_release.v1");
      expect(projectQuoteJson.totals.assetCount).toBe(1);
      expect(projectQuoteJson.totals.estimatedTotal).toBeGreaterThan(0);
      expect(projectQuoteJson.totals.customQuoteRequiredCount).toBe(3);
      expect(projectQuoteJson.categoryTotals.some((item: { category: string }) => item.category === "materials")).toBe(true);
      expect(projectQuoteJson.categoryTotals.some((item: { category: string }) => item.category === "fabrication")).toBe(true);
      expect(projectQuoteJson.categoryTotals.some((item: { category: string }) => item.category === "contingency")).toBe(true);
      expect(projectQuoteJson.assets[0].id).toBe(instanceId);
      expect(projectQuoteJson.rooms[0].assetCount).toBe(1);
      expect(projectQuoteJson.artifacts.some((item: { type: string }) => item.type === "project_quote_package_json")).toBe(true);
      expect(projectQuoteJson.artifacts.some((item: { type: string }) => item.type === "project_procurement_json")).toBe(true);
      expect(projectQuoteJson.artifacts.some((item: { type: string }) => item.type === "project_finish_schedule_json")).toBe(true);
      expect(projectQuoteJson.artifacts.some((item: { type: string }) => item.type === "project_drawing_set_json")).toBe(true);
      expect(projectQuoteJson.artifacts.some((item: { type: string }) => item.type === "project_cut_list_json")).toBe(true);
      expect(projectQuoteJson.artifacts.some((item: { type: string }) => item.type === "project_approval_package_json")).toBe(true);
      expect(projectQuoteJson.artifacts.some((item: { type: string }) => item.type === "project_rfq_json")).toBe(true);
      const projectPurchaseReadinessDownloadPromise = page.waitForEvent("download");
      await page.getByTestId("selected-cabinet-download-project-purchase-readiness").click();
      const projectPurchaseReadinessDownload = await projectPurchaseReadinessDownloadPromise;
      const projectPurchaseReadinessPath = await projectPurchaseReadinessDownload.path();
      expect(projectPurchaseReadinessPath).toBeTruthy();
      expect(projectPurchaseReadinessDownload.suggestedFilename()).toMatch(/purchase-readiness\.json$/);
      const projectPurchaseReadinessJson = JSON.parse(fs.readFileSync(projectPurchaseReadinessPath!, "utf8"));
      expect(projectPurchaseReadinessJson.schema).toBe("custom_millwork.project_purchase_readiness.v1");
      expect(projectPurchaseReadinessJson.purchaseReadiness).toBe("needs_quote");
      expect(projectPurchaseReadinessJson.canCreateCheckout).toBe(false);
      expect(projectPurchaseReadinessJson.canIssuePurchaseOrder).toBe(false);
      expect(projectPurchaseReadinessJson.procurementPackage.schema).toBe("custom_millwork.project_procurement.v1");
      expect(projectPurchaseReadinessJson.quotePackage.schema).toBe("custom_millwork.project_quote.v1");
      expect(projectPurchaseReadinessJson.checkoutPolicy.includeInCheckout).toBe(false);
      expect(projectPurchaseReadinessJson.totals.checkoutCandidateCount).toBe(7);
      expect(projectPurchaseReadinessJson.totals.customQuoteRequiredCount).toBe(3);
      expect(projectPurchaseReadinessJson.totals.estimatedProjectQuoteTotal).toBe(projectQuoteJson.totals.estimatedTotal);
      expect(projectPurchaseReadinessJson.lineItems.some((item: { purchaseAction: string; checkoutEligible: boolean }) => item.purchaseAction === "supplier_catalog_candidate" && item.checkoutEligible === false)).toBe(true);
      expect(projectPurchaseReadinessJson.lineItems.some((item: { purchaseAction: string }) => item.purchaseAction === "requires_custom_quote")).toBe(true);
      expect(projectPurchaseReadinessJson.assets[0].id).toBe(instanceId);
      expect(projectPurchaseReadinessJson.nextActions.some((item: string) => item.toLowerCase().includes("custom"))).toBe(true);
      expect(projectPurchaseReadinessJson.artifacts.some((item: { type: string }) => item.type === "project_purchase_readiness_json")).toBe(true);
      expect(projectPurchaseReadinessJson.artifacts.some((item: { type: string }) => item.type === "project_procurement_json")).toBe(true);
      expect(projectPurchaseReadinessJson.artifacts.some((item: { type: string }) => item.type === "project_finish_schedule_json")).toBe(true);
      expect(projectPurchaseReadinessJson.artifacts.some((item: { type: string }) => item.type === "project_cut_list_json")).toBe(true);
      expect(projectPurchaseReadinessJson.artifacts.some((item: { type: string }) => item.type === "project_quote_package_json")).toBe(true);
      const projectFabricationReleaseDownloadPromise = page.waitForEvent("download");
      await page.getByTestId("selected-cabinet-download-project-fabrication-release").click();
      const projectFabricationReleaseDownload = await projectFabricationReleaseDownloadPromise;
      const projectFabricationReleasePath = await projectFabricationReleaseDownload.path();
      expect(projectFabricationReleasePath).toBeTruthy();
      expect(projectFabricationReleaseDownload.suggestedFilename()).toMatch(/fabrication-release\.json$/);
      const projectFabricationReleaseJson = JSON.parse(fs.readFileSync(projectFabricationReleasePath!, "utf8"));
      expect(projectFabricationReleaseJson.schema).toBe("custom_millwork.project_fabrication_release.v1");
      expect(projectFabricationReleaseJson.status).toBe("needs_review");
      expect(projectFabricationReleaseJson.canReleaseToFabrication).toBe(false);
      expect(projectFabricationReleaseJson.canIssuePurchaseOrder).toBe(false);
      expect(projectFabricationReleaseJson.schedule.schema).toBe("custom_millwork.project_schedule.v1");
      expect(projectFabricationReleaseJson.procurementPackage.schema).toBe("custom_millwork.project_procurement.v1");
      expect(projectFabricationReleaseJson.quoteRequest.schema).toBe("custom_millwork.project_rfq.v1");
      expect(projectFabricationReleaseJson.totals.assetCount).toBe(1);
      expect(projectFabricationReleaseJson.totals.needsReviewCount).toBe(1);
      expect(projectFabricationReleaseJson.assets[0].id).toBe(instanceId);
      expect(projectFabricationReleaseJson.assets[0].fabricationDxfFileName).toMatch(/cut-layout\.dxf$/);
      expect(projectFabricationReleaseJson.assets[0].installerWorkOrderFileName).toMatch(/installer-work-order\.json$/);
      expect(projectFabricationReleaseJson.releaseDecision.requiresHumanApproval).toBe(true);
      expect(projectFabricationReleaseJson.artifacts.some((item: { type: string }) => item.type === "project_fabrication_release_json")).toBe(true);
      expect(projectFabricationReleaseJson.artifacts.some((item: { type: string }) => item.type === "project_finish_schedule_json")).toBe(true);
      expect(projectFabricationReleaseJson.artifacts.some((item: { type: string }) => item.type === "project_drawing_set_json")).toBe(true);
      expect(projectFabricationReleaseJson.artifacts.some((item: { type: string }) => item.type === "project_cut_list_json")).toBe(true);
      expect(projectFabricationReleaseJson.artifacts.some((item: { type: string }) => item.type === "project_installation_plan_json")).toBe(true);
      expect(projectFabricationReleaseJson.artifacts.some((item: { type: string }) => item.type === "project_field_verification_json")).toBe(true);
      expect(projectFabricationReleaseJson.artifacts.some((item: { type: string }) => item.type === "project_cnc_batch_json")).toBe(true);
      expect(projectFabricationReleaseJson.artifacts.some((item: { type: string }) => item.type === "project_approval_package_json")).toBe(true);
      expect(projectFabricationReleaseJson.artifacts.some((item: { type: string; durable: boolean }) => item.type === "fabrication_dxf" && item.durable === false)).toBe(true);
    });

    test("Pro designer can export project approval, production, and handoff packages", async ({
      page,
    }) => {
      const { sourceJson, instanceId } = await placeCabinetRun(page);

      const placedPackagePrerequisite = page.waitForEvent("download");
      await page.getByTestId("selected-cabinet-download-placed-package").click();
      const placedPackagePath = await (await placedPackagePrerequisite).path();
      expect(placedPackagePath).toBeTruthy();
      const placedPackageJson = JSON.parse(fs.readFileSync(placedPackagePath!, "utf8"));

      const projectQuotePrerequisite = page.waitForEvent("download");
      await page.getByTestId("selected-cabinet-download-project-quote").click();
      const projectQuotePath = await (await projectQuotePrerequisite).path();
      expect(projectQuotePath).toBeTruthy();
      const projectQuoteJson = JSON.parse(fs.readFileSync(projectQuotePath!, "utf8"));

      const projectApprovalDownloadPromise = page.waitForEvent("download");
      await page.getByTestId("selected-cabinet-download-project-approval-package").click();
      const projectApprovalDownload = await projectApprovalDownloadPromise;
      const projectApprovalPath = await projectApprovalDownload.path();
      expect(projectApprovalPath).toBeTruthy();
      expect(projectApprovalDownload.suggestedFilename()).toMatch(/approval-package\.json$/);
      const projectApprovalJson = JSON.parse(fs.readFileSync(projectApprovalPath!, "utf8"));
      expect(projectApprovalJson.schema).toBe("custom_millwork.project_approval_package.v1");
      expect(projectApprovalJson.approvalStatus).toBe("needs_review");
      expect(projectApprovalJson.canSubmitForClientApproval).toBe(true);
      expect(projectApprovalJson.canSubmitForFabricatorReview).toBe(true);
      expect(projectApprovalJson.canReleaseAfterSignoff).toBe(false);
      expect(projectApprovalJson.fabricationReleasePackage.schema).toBe("custom_millwork.project_fabrication_release.v1");
      expect(projectApprovalJson.procurementPackage.schema).toBe("custom_millwork.project_procurement.v1");
      expect(projectApprovalJson.totals.approvalItemCount).toBe(7);
      expect(projectApprovalJson.totals.clientApprovalCount).toBe(2);
      expect(projectApprovalJson.totals.fabricatorApprovalCount).toBe(2);
      expect(projectApprovalJson.approvalItems.every((item: { assetId: string }) => item.assetId === instanceId)).toBe(true);
      expect(projectApprovalJson.signoffPolicy.requiresClientApproval).toBe(true);
      expect(projectApprovalJson.artifacts.some((item: { type: string }) => item.type === "project_approval_package_json")).toBe(true);
      expect(projectApprovalJson.artifacts.some((item: { type: string }) => item.type === "project_finish_schedule_json")).toBe(true);
      expect(projectApprovalJson.artifacts.some((item: { type: string }) => item.type === "project_revision_package_json")).toBe(true);
      expect(projectApprovalJson.artifacts.some((item: { type: string }) => item.type === "project_drawing_set_json")).toBe(true);
      expect(projectApprovalJson.artifacts.some((item: { type: string }) => item.type === "project_cut_list_json")).toBe(true);
      const projectRevisionDownloadPromise = page.waitForEvent("download");
      await page.getByTestId("selected-cabinet-download-project-revision-package").click();
      const projectRevisionDownload = await projectRevisionDownloadPromise;
      const projectRevisionPath = await projectRevisionDownload.path();
      expect(projectRevisionPath).toBeTruthy();
      expect(projectRevisionDownload.suggestedFilename()).toMatch(/revision-package\.json$/);
      const projectRevisionJson = JSON.parse(fs.readFileSync(projectRevisionPath!, "utf8"));
      expect(projectRevisionJson.schema).toBe("custom_millwork.project_revision_package.v1");
      expect(projectRevisionJson.currentSchedule.schema).toBe("custom_millwork.project_schedule.v1");
      expect(projectRevisionJson.previousSchedule).toBeUndefined();
      expect(projectRevisionJson.revisionPolicy.baselineComparisonAvailable).toBe(false);
      expect(projectRevisionJson.totals.currentAssetCount).toBe(1);
      expect(projectRevisionJson.totals.previousAssetCount).toBe(0);
      expect(projectRevisionJson.totals.changeItemCount).toBe(0);
      expect(projectRevisionJson.assets[0].id).toBe(instanceId);
      expect(projectRevisionJson.assets[0].revisionStatus).toBe("baseline");
      expect(projectRevisionJson.assets[0].sourceDefinitionFingerprint).toBe(sourceJson.sourceDefinitionFingerprint);
      expect(projectRevisionJson.artifacts.some((item: { type: string }) => item.type === "project_revision_package_json")).toBe(true);
      expect(projectRevisionJson.artifacts.some((item: { type: string }) => item.type === "project_finish_schedule_json")).toBe(true);
      expect(projectRevisionJson.artifacts.some((item: { type: string }) => item.type === "project_approval_package_json")).toBe(true);
      const projectDrawingSetDownloadPromise = page.waitForEvent("download");
      await page.getByTestId("selected-cabinet-download-project-drawing-set").click();
      const projectDrawingSetDownload = await projectDrawingSetDownloadPromise;
      const projectDrawingSetPath = await projectDrawingSetDownload.path();
      expect(projectDrawingSetPath).toBeTruthy();
      expect(projectDrawingSetDownload.suggestedFilename()).toMatch(/drawing-set\.json$/);
      const projectDrawingSetJson = JSON.parse(fs.readFileSync(projectDrawingSetPath!, "utf8"));
      expect(projectDrawingSetJson.schema).toBe("custom_millwork.project_drawing_set.v1");
      expect(projectDrawingSetJson.schedule.schema).toBe("custom_millwork.project_schedule.v1");
      expect(projectDrawingSetJson.revisionPackage.schema).toBe("custom_millwork.project_revision_package.v1");
      expect(projectDrawingSetJson.approvalPackage.schema).toBe("custom_millwork.project_approval_package.v1");
      expect(projectDrawingSetJson.totals.assetCount).toBe(1);
      expect(projectDrawingSetJson.totals.sheetCount).toBe(5);
      expect(projectDrawingSetJson.totals.drawingViewCount).toBe(9);
      expect(projectDrawingSetJson.totals.dimensionRowCount).toBe(4);
      expect(projectDrawingSetJson.totals.frontElevationCount).toBe(4);
      expect(projectDrawingSetJson.totals.sideSectionCount).toBe(4);
      expect(projectDrawingSetJson.totals.planFootprintCount).toBe(1);
      expect(projectDrawingSetJson.assets[0].id).toBe(instanceId);
      expect(projectDrawingSetJson.assets[0].shopDrawingFileName).toMatch(/shop-drawing\.svg$/);
      expect(projectDrawingSetJson.sheets.every((item: { assetId: string }) => item.assetId === instanceId)).toBe(true);
      expect(projectDrawingSetJson.sheets.some((item: { viewTypes: string[] }) => item.viewTypes.includes("front_elevation"))).toBe(true);
      expect(projectDrawingSetJson.sheets.some((item: { viewTypes: string[] }) => item.viewTypes.includes("side_section"))).toBe(true);
      expect(projectDrawingSetJson.sheets.some((item: { viewTypes: string[] }) => item.viewTypes.includes("plan_footprint"))).toBe(true);
      expect(projectDrawingSetJson.drawingReviewPolicy.requiresFabricatorReview).toBe(true);
      expect(projectDrawingSetJson.artifacts.some((item: { type: string }) => item.type === "project_drawing_set_json")).toBe(true);
      expect(projectDrawingSetJson.artifacts.some((item: { type: string }) => item.type === "shop_drawing_svg")).toBe(true);
      expect(projectDrawingSetJson.artifacts.some((item: { type: string }) => item.type === "project_revision_package_json")).toBe(true);
      expect(projectDrawingSetJson.artifacts.some((item: { type: string }) => item.type === "project_cut_list_json")).toBe(true);
      const projectCutListDownloadPromise = page.waitForEvent("download");
      await page.getByTestId("selected-cabinet-download-project-cut-list").click();
      const projectCutListDownload = await projectCutListDownloadPromise;
      const projectCutListPath = await projectCutListDownload.path();
      expect(projectCutListPath).toBeTruthy();
      expect(projectCutListDownload.suggestedFilename()).toMatch(/cut-list\.json$/);
      const projectCutListJson = JSON.parse(fs.readFileSync(projectCutListPath!, "utf8"));
      expect(projectCutListJson.schema).toBe("custom_millwork.project_cut_list.v1");
      expect(projectCutListJson.schedule.schema).toBe("custom_millwork.project_schedule.v1");
      expect(projectCutListJson.drawingSetPackage.schema).toBe("custom_millwork.project_drawing_set.v1");
      expect(projectCutListJson.revisionPackage.schema).toBe("custom_millwork.project_revision_package.v1");
      expect(projectCutListJson.totals.assetCount).toBe(1);
      expect(projectCutListJson.totals.partRowCount).toBe(30);
      expect(projectCutListJson.totals.totalQuantity).toBe(30);
      expect(projectCutListJson.totals.edgeBandingTotalM).toBe(28.23);
      expect(projectCutListJson.assets[0].id).toBe(instanceId);
      expect(projectCutListJson.assets[0].fabricationDxfFileName).toMatch(/cut-layout\.dxf$/);
      expect(projectCutListJson.assets[0].shopDrawingFileName).toMatch(/shop-drawing\.svg$/);
      expect(projectCutListJson.parts).toHaveLength(30);
      expect(projectCutListJson.parts.every((item: { assetId: string }) => item.assetId === instanceId)).toBe(true);
      expect(projectCutListJson.parts.some((item: { edgeBandingM: number }) => item.edgeBandingM > 0)).toBe(true);
      expect(projectCutListJson.materials.length).toBeGreaterThan(0);
      expect(projectCutListJson.materials.every((item: { assetIds: string[] }) => item.assetIds.includes(instanceId!))).toBe(true);
      expect(projectCutListJson.cutListReviewPolicy.requiresCncReview).toBe(true);
      expect(projectCutListJson.artifacts.some((item: { type: string }) => item.type === "project_cut_list_json")).toBe(true);
      expect(projectCutListJson.artifacts.some((item: { type: string }) => item.type === "project_cnc_batch_json")).toBe(true);
      expect(projectCutListJson.artifacts.some((item: { type: string; durable: boolean }) => item.type === "fabrication_dxf" && item.durable === false)).toBe(true);
      expect(projectCutListJson.artifacts.some((item: { type: string }) => item.type === "shop_drawing_svg")).toBe(true);
      const projectCncBatchDownloadPromise = page.waitForEvent("download");
      await page.getByTestId("selected-cabinet-download-project-cnc-batch").click();
      const projectCncBatchDownload = await projectCncBatchDownloadPromise;
      const projectCncBatchPath = await projectCncBatchDownload.path();
      expect(projectCncBatchPath).toBeTruthy();
      expect(projectCncBatchDownload.suggestedFilename()).toMatch(/cnc-batch\.json$/);
      const projectCncBatchJson = JSON.parse(fs.readFileSync(projectCncBatchPath!, "utf8"));
      expect(projectCncBatchJson.schema).toBe("custom_millwork.project_cnc_batch.v1");
      expect(projectCncBatchJson.cncReadiness).toBe("needs_review");
      expect(projectCncBatchJson.fabricationReleasePackage.schema).toBe("custom_millwork.project_fabrication_release.v1");
      expect(projectCncBatchJson.totals.assetCount).toBe(1);
      expect(projectCncBatchJson.totals.dxfFileCount).toBe(1);
      expect(projectCncBatchJson.totals.cutListCount).toBeGreaterThan(0);
      expect(projectCncBatchJson.materials.length).toBeGreaterThan(0);
      expect(projectCncBatchJson.assets[0].id).toBe(instanceId);
      expect(projectCncBatchJson.assets[0].dxfFileName).toMatch(/cut-layout\.dxf$/);
      expect(projectCncBatchJson.assets[0].machiningReviewRequired).toBe(true);
      expect(projectCncBatchJson.materials.every((item: { assetIds: string[] }) => item.assetIds.includes(instanceId!))).toBe(true);
      expect(projectCncBatchJson.artifacts.some((item: { type: string }) => item.type === "project_cnc_batch_json")).toBe(true);
      expect(projectCncBatchJson.artifacts.some((item: { type: string }) => item.type === "project_finish_schedule_json")).toBe(true);
      expect(projectCncBatchJson.artifacts.some((item: { type: string }) => item.type === "project_cut_list_json")).toBe(true);
      expect(projectCncBatchJson.artifacts.some((item: { type: string; durable: boolean }) => item.type === "fabrication_dxf" && item.durable === false)).toBe(true);
      const projectInstallationPlanDownloadPromise = page.waitForEvent("download");
      await page.getByTestId("selected-cabinet-download-project-installation-plan").click();
      const projectInstallationPlanDownload = await projectInstallationPlanDownloadPromise;
      const projectInstallationPlanPath = await projectInstallationPlanDownload.path();
      expect(projectInstallationPlanPath).toBeTruthy();
      expect(projectInstallationPlanDownload.suggestedFilename()).toMatch(/installation-plan\.json$/);
      const projectInstallationPlanJson = JSON.parse(fs.readFileSync(projectInstallationPlanPath!, "utf8"));
      expect(projectInstallationPlanJson.schema).toBe("custom_millwork.project_installation_plan.v1");
      expect(projectInstallationPlanJson.installationReadiness).toBe("needs_review");
      expect(projectInstallationPlanJson.schedule.schema).toBe("custom_millwork.project_schedule.v1");
      expect(projectInstallationPlanJson.fabricationReleasePackage.schema).toBe("custom_millwork.project_fabrication_release.v1");
      expect(projectInstallationPlanJson.totals.assetCount).toBe(1);
      expect(projectInstallationPlanJson.totals.roomCount).toBe(1);
      expect(projectInstallationPlanJson.totals.installerWorkOrderCount).toBe(1);
      expect(projectInstallationPlanJson.assets[0].id).toBe(instanceId);
      expect(projectInstallationPlanJson.assets[0].installSequence).toBe(1);
      expect(projectInstallationPlanJson.assets[0].siteTransform.position).toEqual(placedPackageJson.placedAsset.transform.position);
      expect(projectInstallationPlanJson.assets[0].installerWorkOrderFileName).toMatch(/installer-work-order\.json$/);
      expect(projectInstallationPlanJson.assets[0].estimatedInstallHours).toBeGreaterThan(0);
      expect(projectInstallationPlanJson.rooms[0].assetIds).toContain(instanceId);
      expect(projectInstallationPlanJson.artifacts.some((item: { type: string }) => item.type === "project_installation_plan_json")).toBe(true);
      expect(projectInstallationPlanJson.artifacts.some((item: { type: string }) => item.type === "project_finish_schedule_json")).toBe(true);
      expect(projectInstallationPlanJson.artifacts.some((item: { type: string }) => item.type === "project_field_verification_json")).toBe(true);
      expect(projectInstallationPlanJson.artifacts.some((item: { type: string }) => item.type === "installer_work_order_json")).toBe(true);
      const projectRfqDownloadPromise = page.waitForEvent("download");
      await page.getByTestId("selected-cabinet-download-project-rfq").click();
      const projectRfqDownload = await projectRfqDownloadPromise;
      const projectRfqPath = await projectRfqDownload.path();
      expect(projectRfqPath).toBeTruthy();
      expect(projectRfqDownload.suggestedFilename()).toMatch(/project-rfq\.json$/);
      const projectRfqJson = JSON.parse(fs.readFileSync(projectRfqPath!, "utf8"));
      expect(projectRfqJson.schema).toBe("custom_millwork.project_rfq.v1");
      expect(projectRfqJson.schedule.schema).toBe("custom_millwork.project_schedule.v1");
      expect(projectRfqJson.totals.assetCount).toBe(1);
      expect(projectRfqJson.totals.edgeBandingTotalM).toBe(28.23);
      expect(projectRfqJson.assets[0].id).toBe(instanceId);
      expect(projectRfqJson.assetQuoteRequests).toHaveLength(1);
      expect(projectRfqJson.assetQuoteRequests[0].schema).toBe("custom_millwork.rfq.v1");
      expect(projectRfqJson.artifacts.some((item: { type: string }) => item.type === "project_schedule_json")).toBe(true);
      expect(projectRfqJson.artifacts.some((item: { type: string }) => item.type === "project_schedule_csv")).toBe(true);
      expect(projectRfqJson.artifacts.some((item: { type: string }) => item.type === "project_procurement_json")).toBe(true);
      expect(projectRfqJson.artifacts.some((item: { type: string }) => item.type === "project_finish_schedule_json")).toBe(true);
      expect(projectRfqJson.artifacts.some((item: { type: string }) => item.type === "project_drawing_set_json")).toBe(true);
      expect(projectRfqJson.artifacts.some((item: { type: string }) => item.type === "project_cut_list_json")).toBe(true);
      expect(projectRfqJson.artifacts.some((item: { type: string }) => item.type === "project_quote_package_json")).toBe(true);
      expect(projectRfqJson.artifacts.some((item: { type: string }) => item.type === "project_purchase_readiness_json")).toBe(true);
      expect(projectRfqJson.artifacts.some((item: { type: string }) => item.type === "project_field_verification_json")).toBe(true);
      expect(projectRfqJson.artifacts.some((item: { type: string }) => item.type === "project_fabrication_release_json")).toBe(true);
      expect(projectRfqJson.artifacts.some((item: { type: string }) => item.type === "project_installation_plan_json")).toBe(true);
      expect(projectRfqJson.artifacts.some((item: { type: string }) => item.type === "project_cnc_batch_json")).toBe(true);
      expect(projectRfqJson.artifacts.some((item: { type: string }) => item.type === "project_approval_package_json")).toBe(true);
      expect(projectRfqJson.artifacts.some((item: { type: string }) => item.type === "installer_work_order_json")).toBe(true);
      expect(projectRfqJson.requestedDeliverables.some((item: string) => item.includes("project-level"))).toBe(true);
      const projectHandoffDownloadPromise = page.waitForEvent("download");
      await page.getByTestId("selected-cabinet-download-project-handoff").click();
      const projectHandoffDownload = await projectHandoffDownloadPromise;
      const projectHandoffPath = await projectHandoffDownload.path();
      expect(projectHandoffPath).toBeTruthy();
      expect(projectHandoffDownload.suggestedFilename()).toMatch(/project-handoff\.json$/);
      const projectHandoffJson = JSON.parse(fs.readFileSync(projectHandoffPath!, "utf8"));
      expect(projectHandoffJson.schema).toBe("custom_millwork.project_handoff_package.v1");
      expect(projectHandoffJson.handoffStatus).toBe("needs_review");
      expect(projectHandoffJson.canIssueToClient).toBe(true);
      expect(projectHandoffJson.canIssueToFabricator).toBe(true);
      expect(projectHandoffJson.canIssueToInstaller).toBe(true);
      expect(projectHandoffJson.canIssueForPurchaseReview).toBe(true);
      expect(projectHandoffJson.packages.schedule.schema).toBe("custom_millwork.project_schedule.v1");
      expect(projectHandoffJson.packages.scopePackage.schema).toBe("custom_millwork.project_scope.v1");
      expect(projectHandoffJson.packages.procurementPackage.schema).toBe("custom_millwork.project_procurement.v1");
      expect(projectHandoffJson.packages.drawingSetPackage.schema).toBe("custom_millwork.project_drawing_set.v1");
      expect(projectHandoffJson.packages.cutListPackage.schema).toBe("custom_millwork.project_cut_list.v1");
      expect(projectHandoffJson.packages.cncBatchPackage.schema).toBe("custom_millwork.project_cnc_batch.v1");
      expect(projectHandoffJson.packages.rfqPackage.schema).toBe("custom_millwork.project_rfq.v1");
      expect(projectHandoffJson.totals.assetCount).toBe(1);
      expect(projectHandoffJson.totals.packageCount).toBe(15);
      expect(projectHandoffJson.totals.cutListCount).toBe(30);
      expect(projectHandoffJson.totals.edgeBandingTotalM).toBe(28.23);
      expect(projectHandoffJson.totals.estimatedTotal).toBe(projectQuoteJson.totals.estimatedTotal);
      expect(projectHandoffJson.assets[0].id).toBe(instanceId);
      expect(projectHandoffJson.assets[0].sourceDefinitionFingerprint).toBe(sourceJson.sourceDefinitionFingerprint);
      expect(projectHandoffJson.handoffChecklist.some((item: { id: string; status: string }) => item.id === "handoff:fabrication-release" && item.status === "required")).toBe(true);
      expect(projectHandoffJson.handoffChecklist.some((item: { id: string; status: string }) => item.id === "handoff:checkout-exclusion" && item.status === "ready")).toBe(true);
      expect(projectHandoffJson.artifacts.some((item: { type: string }) => item.type === "project_handoff_package_json")).toBe(true);
      expect(projectHandoffJson.artifacts.some((item: { type: string }) => item.type === "project_scope_json")).toBe(true);
      expect(projectHandoffJson.artifacts.some((item: { type: string }) => item.type === "project_cut_list_json")).toBe(true);
      expect(projectHandoffJson.artifacts.some((item: { type: string }) => item.type === "project_cnc_batch_json")).toBe(true);
      expect(projectHandoffJson.artifacts.some((item: { type: string }) => item.type === "project_rfq_json")).toBe(true);
      expect(projectHandoffJson.artifacts.some((item: { type: string }) => item.type === "installer_work_order_json")).toBe(true);
    });

  });
}
