import type { CabinetMaterialRef } from "../types";

export type CabinetMaterialCatalogItem = CabinetMaterialRef & {
  skuId?: string;
  pricePlaceholder?: number;
};

export const CABINET_MATERIALS: CabinetMaterialCatalogItem[] = [
  {
    id: "white_melamine",
    name: "White melamine",
    color: "#f5f3ec",
    roughness: 0.62,
    metalness: 0,
    skuId: "CAB-MAT-WHITE-MEL",
    grainBehavior: "non_directional",
    matchingEdgeSkuId: "CAB-MAT-WHITE-MEL-EDGE",
    supportedEdgeTreatments: ["matching_edge_band", "contrasting_edge_band", "solid_lipping", "none"],
  },
  {
    id: "oak_veneer",
    name: "Oak veneer",
    color: "#caa56f",
    roughness: 0.55,
    metalness: 0,
    skuId: "CAB-MAT-OAK-VNR",
    grainBehavior: "directional",
    matchingEdgeSkuId: "CAB-MAT-OAK-VNR-EDGE",
    supportedEdgeTreatments: ["matching_edge_band", "contrasting_edge_band", "solid_lipping", "none"],
  },
  {
    id: "walnut_veneer",
    name: "Walnut veneer",
    color: "#765038",
    roughness: 0.58,
    metalness: 0,
    skuId: "CAB-MAT-WAL-VNR",
    grainBehavior: "directional",
    matchingEdgeSkuId: "CAB-MAT-WAL-VNR-EDGE",
    supportedEdgeTreatments: ["matching_edge_band", "contrasting_edge_band", "solid_lipping", "none"],
  },
  {
    id: "matte_black_laminate",
    name: "Matte black laminate",
    color: "#1f2326",
    roughness: 0.84,
    metalness: 0,
    skuId: "CAB-MAT-BLK-LAM",
    grainBehavior: "non_directional",
    matchingEdgeSkuId: "CAB-MAT-BLK-LAM-EDGE",
    supportedEdgeTreatments: ["matching_edge_band", "contrasting_edge_band", "solid_lipping", "none"],
  },
  {
    id: "painted_shaker_white",
    name: "Painted shaker white",
    color: "#fffaf0",
    roughness: 0.68,
    metalness: 0,
    skuId: "CAB-MAT-SHK-WHT",
    grainBehavior: "non_directional",
    matchingEdgeSkuId: "CAB-MAT-SHK-WHT-EDGE",
    supportedEdgeTreatments: ["painted_edge", "matching_edge_band", "solid_lipping", "none"],
  },
  {
    id: "glass",
    name: "Glass",
    color: "#c9e5ee",
    roughness: 0.1,
    metalness: 0,
    skuId: "CAB-MAT-GLASS",
    grainBehavior: "non_directional",
    supportedEdgeTreatments: ["none"],
  },
  {
    id: "upholstery_neutral",
    name: "Neutral upholstery",
    color: "#d8cfc3",
    roughness: 0.9,
    metalness: 0,
    skuId: "CAB-MAT-UPH-NEUTRAL",
    grainBehavior: "non_directional",
    supportedEdgeTreatments: ["none"],
  },
  {
    id: "service_zone_marker",
    name: "Service zone marker",
    color: "#2563eb",
    roughness: 0.35,
    metalness: 0,
    skuId: "CAB-MAT-SVC-MARKER",
    grainBehavior: "non_directional",
    supportedEdgeTreatments: ["none"],
  },
];
