import { expect, test } from "@playwright/test";
import { writeFile } from "node:fs/promises";
import { authoredApartment } from "../../scripts/fixtures/scan-to-editable-plan/apartment";
import { canonicalFloorPlanToDesignSnapshot } from "../../lib/floor-plan-legacy-adapters";
import { snapshotToStored, type StoredDesign } from "../../lib/room-persistence";
import { compileCanonicalFloorPlanRenderModel } from "../../lib/floor-plan-render-model";
import { observeRenderedScene, renderedSceneObject } from "./rendered-scene-observer";
import { exerciseFurnitureWalls } from "./furniture-wall-journey";

test("Consumer replacement doorway, catalog furniture, undo and saved reload", async ({ page }, testInfo) => {
  await observeRenderedScene(page);
  const key = "interior-ai:v1:livingroom-design", errors: string[] = [];
  page.on("pageerror", (error) => errors.push(error.message));
  const initial = snapshotToStored(canonicalFloorPlanToDesignSnapshot(authoredApartment()).snapshot);
  await page.addInitScript(({ key, initial }) => {
    if (!localStorage.getItem(key)) localStorage.setItem(key, JSON.stringify(initial));
    localStorage.setItem("interior-ai:beta-start-dismissed", "1");
  }, { key, initial });
  const saved = (): Promise<StoredDesign> => page.evaluate((key) => JSON.parse(localStorage.getItem(key) ?? "null"), key);
  const document = async () => (await saved()).floorPlan!.canonicalDocument!;
  const items = async () => (await saved()).rooms!.flatMap((room) => room.items.map((item) => ({ roomId: room.id, ...item, locked: item.locked ?? false })));
  await page.goto("/design");
  await page.getByRole("button", { name: "Yes, it matches", exact: true }).click();
  await page.getByTestId("editor-view-2d").click();
  const panel = page.getByTestId("imported-wall-editor");
  await panel.getByTestId("request-edit-imported-walls").click();
  await panel.getByTestId("confirm-edit-local-floor-plan").click();
  await panel.getByLabel("Wall", { exact: true }).selectOption("shared");
  await panel.locator("summary", { hasText: "Remove selected wall" }).click();
  await panel.getByLabel("Keep name and finishes from").selectOption("living");
  await panel.getByRole("checkbox").check();
  await panel.getByRole("button", { name: "Remove proposed wall", exact: true }).click();
  await expect.poll(async () => (await document()).floors[0].rooms.length).toBe(1);
  await panel.locator("summary", { hasText: "Add a wall" }).click();
  for (const [label, value] of [["Start X (mm)", "3000"], ["Start Z (mm)", "0"], ["End X (mm)", "3000"], ["End Z (mm)", "6000"]]) {
    await panel.getByLabel(label, { exact: true }).fill(value);
  }
  await panel.getByLabel("New room name if divided").fill("Study");
  await panel.getByRole("button", { name: "Add proposed wall", exact: true }).click();
  await expect.poll(async () => (await document()).floors[0].rooms.length).toBe(2);
  const partition = (await document()).floors[0].walls.find(({ id }) => id.startsWith("wall-"))!;
  await panel.getByLabel("Wall", { exact: true }).selectOption(partition.id);
  await expect(page.getByTestId("room-setup-continue-furnish")).toBeDisabled();
  await panel.locator("summary", { hasText: "Doors and windows" }).click();
  await panel.getByRole("combobox", { name: "Type", exact: true }).selectOption("door");
  await panel.getByRole("combobox", { name: "Operation", exact: true }).selectOption("swing");
  for (const [label, value] of [["Position from wall start (mm)", "2500"], ["Width (mm)", "900"], ["Height (mm)", "2100"], ["Sill (mm)", "0"]]) {
    await panel.getByLabel(label, { exact: true }).fill(value);
  }
  await panel.getByRole("combobox", { name: "Hinge", exact: true }).selectOption("end");
  await panel.getByRole("combobox", { name: "Swing side", exact: true }).selectOption("right");
  await panel.getByRole("button", { name: "Add opening", exact: true }).click();
  await expect.poll(async () => (await document()).floors[0].openings.length).toBe(2);
  const door = (await document()).floors[0].openings.find(({ wallId }) => wallId === partition.id)!;
  expect(door).toMatchObject({ kind: "door", offsetMm: 2500, widthMm: 900, hinge: "end", handing: "right" });
  await expect(page.getByTestId("room-setup-continue-furnish")).toBeEnabled();
  await page.getByTestId("room-setup-continue-furnish").click();
  const search = page.getByTestId("catalog-search-input");
  await expect(search).toBeVisible();
  await page.getByTestId("furnish-room-target-select").selectOption({ label: "Living" });
  await search.fill("Madison");
  const productId = "sofa-real-castlery-madison-2s";
  await page.getByTestId(`catalog-preview-${productId}`).click();
  await expect(page.getByTestId("catalog-item-drawer")).toContainText("Madison Sofa");
  await page.getByTestId("catalog-detail-add-to-room").click();
  await expect(page.getByTestId("catalog-placement-confirm-panel")).toBeVisible();
  await expect(page.getByTestId("catalog-placement-target-room")).toContainText("Living");
  await expect(page.getByTestId("catalog-placement-score-card")).toBeVisible();
  await expect(page.getByTestId("catalog-placement-confirm")).toBeEnabled();
  const accepted = await document();
  await page.getByTestId("catalog-placement-confirm").click();
  await expect.poll(async () => (await items()).length).toBe(1);
  const placed = await items();
  await expect.poll(async () => (await saved()).rooms!.find(({ id }) => id === placed[0].roomId)!.zones.length).toBeGreaterThan(0);
  const placedZones = (await saved()).rooms!.find(({ id }) => id === placed[0].roomId)!.zones;
  expect(placed[0].productId).toBe(productId);
  expect(await document()).toEqual(accepted);
  await page.getByRole("button", { name: /^Undo/ }).click();
  await expect.poll(items).toEqual([]);
  expect((await saved()).rooms!.find(({ id }) => id === placed[0].roomId)!.zones).toEqual([]);
  await page.getByRole("button", { name: /^Redo/ }).click();
  await expect.poll(items).toEqual(placed);
  expect((await saved()).rooms!.find(({ id }) => id === placed[0].roomId)!.zones).toEqual(placedZones);
  await exerciseFurnitureWalls(page, saved, testInfo);
  await expect(page.getByTestId("scene-ready-veil")).toBeHidden();
  const rendered2d = await renderedSceneObject(page, { itemId: placed[0].instanceId });
  expect(rendered2d).not.toBeNull();
  await page.screenshot({ path: testInfo.outputPath("furnished-2d.png") });
  await page.getByTestId("editor-view-3d").click();
  await expect(page.getByTestId("scene-ready-veil")).toBeHidden();
  await expect.poll(async () => Boolean(await renderedSceneObject(page, { itemId: placed[0].instanceId }))).toBe(true);
  const rendered3d = (await renderedSceneObject(page, { itemId: placed[0].instanceId }))!;
  const room = (await saved()).rooms!.find(({ id }) => id === placed[0].roomId)!;
  expect(rendered3d.world[0]).toBeCloseTo(placed[0].position[0] + (room.planPosition?.x ?? 0), 5);
  expect(rendered3d.world[2]).toBeCloseTo(placed[0].position[2] + (room.planPosition?.z ?? 0), 5);
  const door3d = await renderedSceneObject(page, { testId: "canonical-opening-3d", openingId: door.id });
  expect(door3d?.userData.canonicalGeometryHash).toBe(compileCanonicalFloorPlanRenderModel(accepted).geometryHash);
  await page.screenshot({ path: testInfo.outputPath("furnished-3d.png") });
  expect(await document()).toEqual(accepted);
  expect(await items()).toEqual(placed);
  await page.reload();
  await expect(page.getByTestId("editor-view-2d")).toBeVisible();
  expect(await items()).toEqual(placed);
  expect(await document()).toEqual(accepted);
  expect((await saved()).floorPlan!.proposal!.originalDocument).toEqual(authoredApartment());
  await writeFile(testInfo.outputPath("furnishing-evidence.json"), JSON.stringify({ accepted, placed, placedZones, rendered2d, rendered3d, door3d, geometryHash: compileCanonicalFloorPlanRenderModel(accepted).geometryHash,
    checks: ["shared wall and hosted door removed", "replacement room division", "door hinge and swing", "connection readiness", "real catalog confirmation", "undo/redo", "view switch and saved reload"] }, null, 2));
  expect(errors).toEqual([]);
});
