import { auth } from "@/lib/auth";
import { NextRequest, NextResponse } from "next/server";
import { PDFDocument, StandardFonts, rgb } from "pdf-lib";
import { rateLimit } from "@/lib/rateLimit";

export const runtime = "nodejs";
export const dynamic = "force-dynamic";

type PdfItem = {
  name: string;
  price: number;
  qty?: number;
  retailer?: string | null;
};

type PdfPayload = {
  title?: string;
  items?: PdfItem[];
  images?: string[];
};

const MAX_IMAGE_BYTES = 10 * 1024 * 1024;

const withTimeout = async <T,>(promise: Promise<T>, ms: number, label: string) => {
  let timeoutId: NodeJS.Timeout | null = null;
  const timeout = new Promise<never>((_, reject) => {
    timeoutId = setTimeout(() => reject(new Error(`${label} timed out`)), ms);
  });
  try {
    return await Promise.race([promise, timeout]);
  } finally {
    if (timeoutId) clearTimeout(timeoutId);
  }
};

const decodeBase64Image = (dataUrl: string) => {
  const match = dataUrl.match(/^data:image\/(png|jpeg);base64,(.+)$/i);
  if (!match) return null;
  const type = match[1].toLowerCase();
  const base64 = match[2];
  const buffer = Buffer.from(base64, "base64");
  if (buffer.length > MAX_IMAGE_BYTES) return null;
  return { buffer, type } as const;
};

export async function POST(req: NextRequest) {
  try {
    const session = await auth();
    if (!session?.user?.id) {
      return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
    }

    const rl = rateLimit(`export:${session.user.id}`, 6, 60_000);
    if (!rl.ok) {
      return NextResponse.json({ error: "Too many export requests" }, { status: 429 });
    }

    const body = (await req.json().catch(() => ({}))) as PdfPayload;
    const title = typeof body.title === "string" && body.title.trim()
      ? body.title.trim()
      : "Interior AI Room Design";
    const items = Array.isArray(body.items) ? body.items : [];
    const images = Array.isArray(body.images) ? body.images.slice(0, 3) : [];

    const pdfDoc = await PDFDocument.create();
    let page = pdfDoc.addPage([612, 792]);
    const { width, height } = page.getSize();
    const margin = 40;
    let y = height - margin;

    const fontRegular = await pdfDoc.embedFont(StandardFonts.Helvetica);
    const fontBold = await pdfDoc.embedFont(StandardFonts.HelveticaBold);

    page.drawText(title, {
      x: margin,
      y: y - 8,
      size: 20,
      font: fontBold,
      color: rgb(0, 0, 0),
    });

    y -= 32;
    page.drawText(`Generated by Interior AI • ${new Date().toLocaleDateString()}`, {
      x: margin,
      y,
      size: 10,
      font: fontRegular,
      color: rgb(0.4, 0.4, 0.4),
    });

    y -= 24;

    if (images.length) {
      const imageWidth = width - margin * 2;
      const imageHeight = 120;
      for (const dataUrl of images) {
        const decoded = decodeBase64Image(dataUrl);
        if (!decoded) continue;
        const embedPromise =
          decoded.type === "jpeg"
            ? pdfDoc.embedJpg(decoded.buffer)
            : pdfDoc.embedPng(decoded.buffer);
        const embedded = await withTimeout(embedPromise, 5000, "Image embed");
        page.drawImage(embedded, {
          x: margin,
          y: y - imageHeight,
          width: imageWidth,
          height: imageHeight,
        });
        y -= imageHeight + 16;
        if (y < margin + 200) break;
      }
    }

    page.drawText("Room Items", {
      x: margin,
      y,
      size: 12,
      font: fontBold,
      color: rgb(0, 0, 0),
    });
    y -= 16;

    let total = 0;
    for (const item of items) {
      if (!item || typeof item.name !== "string" || typeof item.price !== "number") {
        continue;
      }

      const qty = item.qty || 1;
      const itemTotal = item.price * qty;
      total += itemTotal;

      if (y < margin + 60) {
        page = pdfDoc.addPage([612, 792]);
        y = page.getSize().height - margin;
        page.drawText("Room Items (cont.)", {
          x: margin,
          y,
          size: 12,
          font: fontBold,
        });
        y -= 16;
      }

      page.drawText(item.name, {
        x: margin,
        y,
        size: 11,
        font: fontBold,
        color: rgb(0, 0, 0),
      });
      y -= 14;

      if (item.retailer) {
        page.drawText(`Retailer: ${item.retailer}`, {
          x: margin,
          y,
          size: 9,
          font: fontRegular,
          color: rgb(0.35, 0.35, 0.35),
        });
        y -= 12;
      }

      const qtyText = qty > 1 ? `, Qty: ${qty}` : "";
      page.drawText(`Price: $${item.price.toFixed(2)}${qtyText}`, {
        x: margin,
        y,
        size: 9,
        font: fontRegular,
        color: rgb(0.35, 0.35, 0.35),
      });
      y -= 16;
    }

    page.drawText(`Total Budget: $${total.toFixed(2)}`, {
      x: margin,
      y: Math.max(y, margin),
      size: 11,
      font: fontBold,
      color: rgb(0.1, 0.1, 0.1),
    });

    const pdfBytes = await pdfDoc.save();
    const filename = `room-design-${Date.now()}.pdf`;

    return new NextResponse(Buffer.from(pdfBytes), {
      status: 200,
      headers: {
        "Content-Type": "application/pdf",
        "Content-Disposition": `attachment; filename="${filename}"`,
        "Cache-Control": "no-cache, no-store, must-revalidate",
      },
    });
  } catch (err) {
    console.error("PDF export error:", err);
    return NextResponse.json(
      { error: err instanceof Error ? err.message : "PDF generation failed" },
      { status: 500 }
    );
  }
}
