// Extracted from app/design/page.tsx — Phase C modularization
// GLB rendering calibration data for imported real-product models.

export type GLBCalibration = {
  brightness?: number;
  saturation?: number;
  variantMapTintStrength?: number;
  normalScale?: number;
  importedNormalScale?: number;
  roughnessScale?: number;
  roughnessOverride?: number;
  metalnessOverride?: number;
  aoMapIntensity?: number;
  emissiveBoost?: number;
  specularIntensityOverride?: number;
  clearcoatOverride?: number;
  clearcoatRoughnessOverride?: number;
  forceBaseColorHex?: string;
  disableAoMap?: boolean;
  disableVertexColors?: boolean;
  disableBaseColorMap?: boolean;
  disableShadingMaps?: boolean;
  useVariantColor?: boolean;
  swapWidthDepthAxes?: boolean;
  uniformScale?: boolean;
  lockVerticalScaleToFootprint?: boolean;
  preserveWoodLegMaterials?: boolean;
  preserveWoodLegOriginalColor?: boolean;
  preserveWoodLegColorHex?: string;
  preserveWoodLegDisableBaseColorMap?: boolean;
  woodLegDetectionMode?: "default" | "kelsey" | "harper";
  lowerAssemblyTintHex?: string;
  lowerAssemblyTintStrength?: number;
  lowerAssemblyFadeStart?: number;
  lowerAssemblyFadeEnd?: number;
  upperUpholsteryTint?: boolean;
  upperUpholsteryTintStrength?: number;
  upperUpholsteryPreserveSourceLuma?: boolean;
  upperUpholsteryFadeStart?: number;
  upperUpholsteryFadeEnd?: number;
  upperUpholsteryPreserveWarmWood?: boolean;
};

export const STANDARD_IMPORTED_CASTLERY_SOFA_CALIBRATION: GLBCalibration = {
  brightness: 0.74,
  saturation: 1.32,
  variantMapTintStrength: 1,
  normalScale: 4.2,
  roughnessOverride: 0.68,
  metalnessOverride: 0,
  aoMapIntensity: 0.35,
  emissiveBoost: 0,
  specularIntensityOverride: 0.2,
  disableAoMap: true,
  disableVertexColors: true,
  disableBaseColorMap: true,
  disableShadingMaps: true,
  useVariantColor: true,
};

const HAMILTON_SOFA_PRODUCT_IDS = [
  "sofa-real-castlery-hamilton-2-seater",
  "sofa-real-castlery-hamilton-2-seater-with-storage-ottoman",
  "sofa-real-castlery-hamilton-3-seater",
  "sofa-real-castlery-hamilton-3-seater-with-storage-ottoman",
  "sofa-real-castlery-hamilton-chaise-sectional-left",
  "sofa-real-castlery-hamilton-chaise-sectional-right",
  "sofa-real-castlery-hamilton-chaise-sectional-with-storage-ottoman-left",
  "sofa-real-castlery-hamilton-chaise-sectional-with-storage-ottoman-right",
  "sofa-real-castlery-hamilton-round-chaise-sectional-left",
  "sofa-real-castlery-hamilton-round-chaise-sectional-right",
  "armchair-real-castlery-hamilton-round-swivel-armchair",
  "armchair-real-castlery-hamilton-round-swivel-1-5-seater-armchair",
];

const HAMILTON_SOFA_CALIBRATION: GLBCalibration = {
  brightness: 1,
  saturation: 1,
  roughnessOverride: 0.86,
  metalnessOverride: 0,
  aoMapIntensity: 0.24,
  emissiveBoost: 0,
  specularIntensityOverride: 0.08,
  disableAoMap: false,
  disableVertexColors: true,
  useVariantColor: true,
  upperUpholsteryTint: true,
  upperUpholsteryTintStrength: 1,
  upperUpholsteryPreserveSourceLuma: false,
  upperUpholsteryFadeStart: 0.06,
  upperUpholsteryFadeEnd: 0.14,
};

export const GLB_CALIBRATION_BY_PRODUCT_ID: Record<string, GLBCalibration> = {
  ...Object.fromEntries(
    HAMILTON_SOFA_PRODUCT_IDS.map((productId) => [productId, HAMILTON_SOFA_CALIBRATION]),
  ),
  "sofa-real-castlery-dawson-3s": {
    brightness: 0.74,
    saturation: 1.32,
    variantMapTintStrength: 1,
    normalScale: 4.2,
    roughnessOverride: 0.68,
    metalnessOverride: 0,
    aoMapIntensity: 0.35,
    emissiveBoost: 0,
    specularIntensityOverride: 0.2,
    disableAoMap: true,
    disableVertexColors: true,
    disableBaseColorMap: true,
    disableShadingMaps: true,
    useVariantColor: true,
  },
  "sofa-real-castlery-dawson-extended-sofa": {
    brightness: 0.74,
    saturation: 1.32,
    variantMapTintStrength: 1,
    normalScale: 4.2,
    roughnessOverride: 0.68,
    metalnessOverride: 0,
    aoMapIntensity: 0.35,
    emissiveBoost: 0,
    specularIntensityOverride: 0.2,
    disableAoMap: true,
    disableVertexColors: true,
    disableBaseColorMap: true,
    disableShadingMaps: true,
    useVariantColor: true,
  },
  "sofa-real-castlery-dawson-ottoman": {
    brightness: 0.74,
    saturation: 1.32,
    variantMapTintStrength: 1,
    normalScale: 4.2,
    roughnessOverride: 0.68,
    metalnessOverride: 0,
    aoMapIntensity: 0.35,
    emissiveBoost: 0,
    specularIntensityOverride: 0.2,
    disableAoMap: true,
    disableVertexColors: true,
    disableBaseColorMap: true,
    disableShadingMaps: true,
    useVariantColor: true,
  },
  "sofa-real-castlery-dawson-storage-ottoman": {
    brightness: 0.74,
    saturation: 1.32,
    variantMapTintStrength: 1,
    normalScale: 4.2,
    roughnessOverride: 0.68,
    metalnessOverride: 0,
    aoMapIntensity: 0.35,
    emissiveBoost: 0,
    specularIntensityOverride: 0.2,
    disableAoMap: true,
    disableVertexColors: true,
    disableBaseColorMap: true,
    disableShadingMaps: true,
    useVariantColor: true,
    lockVerticalScaleToFootprint: true,
  },
  "sofa-real-castlery-dawson-pit-sectional": {
    brightness: 0.74,
    saturation: 1.32,
    variantMapTintStrength: 1,
    normalScale: 4.2,
    roughnessOverride: 0.68,
    metalnessOverride: 0,
    aoMapIntensity: 0.35,
    emissiveBoost: 0,
    specularIntensityOverride: 0.2,
    disableAoMap: true,
    disableVertexColors: true,
    disableBaseColorMap: true,
    disableShadingMaps: true,
    useVariantColor: true,
  },
  "sofa-real-castlery-dawson-swivel-armchair": {
    brightness: 0.74,
    saturation: 1.32,
    variantMapTintStrength: 1,
    normalScale: 4.2,
    roughnessOverride: 0.68,
    metalnessOverride: 0,
    aoMapIntensity: 0.35,
    emissiveBoost: 0,
    specularIntensityOverride: 0.2,
    disableAoMap: true,
    disableVertexColors: true,
    disableBaseColorMap: true,
    disableShadingMaps: true,
    useVariantColor: true,
  },
  "sofa-real-castlery-dawson-wide-chaise-sectional": {
    brightness: 0.74,
    saturation: 1.32,
    variantMapTintStrength: 1,
    normalScale: 4.2,
    roughnessOverride: 0.68,
    metalnessOverride: 0,
    aoMapIntensity: 0.35,
    emissiveBoost: 0,
    specularIntensityOverride: 0.2,
    disableAoMap: true,
    disableVertexColors: true,
    disableBaseColorMap: true,
    disableShadingMaps: true,
    useVariantColor: true,
  },
  "sofa-real-castlery-dawson-wide-chaise-sectional-left": {
    brightness: 0.74,
    saturation: 1.32,
    variantMapTintStrength: 1,
    normalScale: 4.2,
    roughnessOverride: 0.68,
    metalnessOverride: 0,
    aoMapIntensity: 0.35,
    emissiveBoost: 0,
    specularIntensityOverride: 0.2,
    disableAoMap: true,
    disableVertexColors: true,
    disableBaseColorMap: true,
    disableShadingMaps: true,
    useVariantColor: true,
  },
  "sofa-real-castlery-madison-2s": {
    brightness: 1.08,
    saturation: 1,
    roughnessOverride: 0.9,
    metalnessOverride: 0,
    aoMapIntensity: 0.25,
    emissiveBoost: 0.06,
    specularIntensityOverride: 0.15,
    disableAoMap: false,
    disableVertexColors: true,
    useVariantColor: true,
    preserveWoodLegMaterials: true,
    preserveWoodLegColorHex: "#8a5b34",
  },
  "armchair-real-castlery-madison-armchair": {
    brightness: 1.08,
    saturation: 1,
    roughnessOverride: 0.9,
    metalnessOverride: 0,
    aoMapIntensity: 0.25,
    emissiveBoost: 0.06,
    specularIntensityOverride: 0.15,
    disableAoMap: false,
    disableVertexColors: true,
    useVariantColor: true,
    preserveWoodLegMaterials: true,
    preserveWoodLegColorHex: "#8a5b34",
  },
  "armchair-real-castlery-arden-performance-swivel-armchair": {
    brightness: 1.04,
    saturation: 1,
    roughnessOverride: 0.86,
    metalnessOverride: 0,
    aoMapIntensity: 0.25,
    emissiveBoost: 0.04,
    specularIntensityOverride: 0.16,
    disableAoMap: false,
    disableVertexColors: true,
    useVariantColor: true,
  },
  "armchair-real-castlery-cammy-armchair": {
    brightness: 1.04,
    saturation: 1,
    roughnessOverride: 0.9,
    metalnessOverride: 0,
    aoMapIntensity: 0.28,
    emissiveBoost: 0.04,
    specularIntensityOverride: 0.12,
    disableAoMap: false,
    disableVertexColors: true,
    useVariantColor: true,
    preserveWoodLegMaterials: true,
    preserveWoodLegColorHex: "#252525",
  },
  "armchair-real-castlery-lena-leather-armchair-cocoa-brass-legs": {
    brightness: 1.04,
    saturation: 1,
    roughnessOverride: 0.88,
    metalnessOverride: 0,
    aoMapIntensity: 0.28,
    emissiveBoost: 0.04,
    specularIntensityOverride: 0.14,
    disableAoMap: false,
    disableVertexColors: true,
    useVariantColor: true,
    preserveWoodLegMaterials: true,
    preserveWoodLegOriginalColor: true,
  },
  "armchair-real-castlery-lena-leather-armchair-cocoa-black-legs": {
    brightness: 1.04,
    saturation: 1,
    roughnessOverride: 0.88,
    metalnessOverride: 0,
    aoMapIntensity: 0.28,
    emissiveBoost: 0.04,
    specularIntensityOverride: 0.14,
    disableAoMap: false,
    disableVertexColors: true,
    useVariantColor: true,
    preserveWoodLegMaterials: true,
    preserveWoodLegOriginalColor: true,
  },
  "armchair-real-castlery-avery-performance-armchair-with-ottoman": {
    swapWidthDepthAxes: true,
  },
  "armchair-real-castlery-avery-performance-swivel-armchair-with-ottoman": {
    swapWidthDepthAxes: true,
  },
  "armchair-real-castlery-solange-performance-boucle-chair-white-wash-legs": {
    brightness: 1.03,
    saturation: 1,
    roughnessOverride: 0.86,
    metalnessOverride: 0,
    aoMapIntensity: 0.24,
    emissiveBoost: 0.04,
    specularIntensityOverride: 0.14,
    disableAoMap: false,
    disableVertexColors: true,
    useVariantColor: true,
    upperUpholsteryTint: true,
    upperUpholsteryTintStrength: 0.82,
    upperUpholsteryFadeStart: 0.04,
    upperUpholsteryFadeEnd: 0.12,
    upperUpholsteryPreserveWarmWood: true,
  },
  "armchair-real-castlery-solange-performance-boucle-chair-black-legs": {
    brightness: 1.03,
    saturation: 1,
    roughnessOverride: 0.86,
    metalnessOverride: 0,
    aoMapIntensity: 0.24,
    emissiveBoost: 0.04,
    specularIntensityOverride: 0.14,
    disableAoMap: false,
    disableVertexColors: true,
    useVariantColor: true,
    upperUpholsteryTint: true,
    upperUpholsteryTintStrength: 0.82,
    upperUpholsteryFadeStart: 0.04,
    upperUpholsteryFadeEnd: 0.12,
    upperUpholsteryPreserveWarmWood: true,
  },
  "armchair-real-castlery-owen-armchair": {
    brightness: 1.03,
    saturation: 1,
    roughnessOverride: 0.84,
    metalnessOverride: 0,
    aoMapIntensity: 0.24,
    emissiveBoost: 0.04,
    specularIntensityOverride: 0.14,
    disableAoMap: false,
    disableVertexColors: true,
    useVariantColor: true,
    upperUpholsteryTint: true,
    upperUpholsteryTintStrength: 0.82,
    upperUpholsteryFadeStart: 0.16,
    upperUpholsteryFadeEnd: 0.26,
  },
  "armchair-real-castlery-owen-armchair-natural-wood": {
    brightness: 1.03,
    saturation: 1,
    roughnessOverride: 0.84,
    metalnessOverride: 0,
    aoMapIntensity: 0.24,
    emissiveBoost: 0.04,
    specularIntensityOverride: 0.14,
    disableAoMap: false,
    disableVertexColors: true,
    useVariantColor: true,
    upperUpholsteryTint: true,
    upperUpholsteryTintStrength: 0.82,
    upperUpholsteryFadeStart: 0.16,
    upperUpholsteryFadeEnd: 0.26,
  },
  "armchair-real-castlery-owen-armchair-walnut-wood": {
    brightness: 1.03,
    saturation: 1,
    roughnessOverride: 0.84,
    metalnessOverride: 0,
    aoMapIntensity: 0.24,
    emissiveBoost: 0.04,
    specularIntensityOverride: 0.14,
    disableAoMap: false,
    disableVertexColors: true,
    useVariantColor: true,
    upperUpholsteryTint: true,
    upperUpholsteryTintStrength: 0.82,
    upperUpholsteryFadeStart: 0.16,
    upperUpholsteryFadeEnd: 0.26,
  },
  "sofa-real-castlery-owen-3-seater": {
    brightness: 1.03,
    saturation: 1,
    roughnessOverride: 0.84,
    metalnessOverride: 0,
    aoMapIntensity: 0.24,
    emissiveBoost: 0.04,
    specularIntensityOverride: 0.14,
    disableAoMap: false,
    disableVertexColors: true,
    useVariantColor: true,
    upperUpholsteryTint: true,
    upperUpholsteryTintStrength: 0.82,
    upperUpholsteryFadeStart: 0.16,
    upperUpholsteryFadeEnd: 0.26,
    upperUpholsteryPreserveWarmWood: true,
  },
  "sofa-real-castlery-owen-chaise-sectional-left": {
    brightness: 1.03,
    saturation: 1,
    roughnessOverride: 0.84,
    metalnessOverride: 0,
    aoMapIntensity: 0.24,
    emissiveBoost: 0.04,
    specularIntensityOverride: 0.14,
    disableAoMap: false,
    disableVertexColors: true,
    useVariantColor: true,
    upperUpholsteryTint: true,
    upperUpholsteryTintStrength: 0.82,
    upperUpholsteryFadeStart: 0.16,
    upperUpholsteryFadeEnd: 0.26,
    upperUpholsteryPreserveWarmWood: true,
  },
  "sofa-real-castlery-owen-chaise-sectional-right": {
    brightness: 1.03,
    saturation: 1,
    roughnessOverride: 0.84,
    metalnessOverride: 0,
    aoMapIntensity: 0.24,
    emissiveBoost: 0.04,
    specularIntensityOverride: 0.14,
    disableAoMap: false,
    disableVertexColors: true,
    useVariantColor: true,
    upperUpholsteryTint: true,
    upperUpholsteryTintStrength: 0.82,
    upperUpholsteryFadeStart: 0.16,
    upperUpholsteryFadeEnd: 0.26,
    upperUpholsteryPreserveWarmWood: true,
  },
  "armchair-real-castlery-winora-armchair": {
    brightness: 1.03,
    saturation: 1,
    roughnessOverride: 0.86,
    metalnessOverride: 0,
    aoMapIntensity: 0.24,
    emissiveBoost: 0.04,
    specularIntensityOverride: 0.14,
    disableAoMap: false,
    disableVertexColors: true,
    useVariantColor: true,
    upperUpholsteryTint: true,
    upperUpholsteryTintStrength: 0.82,
    upperUpholsteryFadeStart: 0.12,
    upperUpholsteryFadeEnd: 0.24,
    upperUpholsteryPreserveWarmWood: true,
  },
  "sofa-real-castlery-jaron-3s": {
    brightness: 1.03,
    saturation: 1.05,
    roughnessOverride: 0.44,
    metalnessOverride: 0.04,
    aoMapIntensity: 0.36,
    emissiveBoost: 0,
    specularIntensityOverride: 0.58,
    clearcoatOverride: 0.22,
    clearcoatRoughnessOverride: 0.6,
    disableAoMap: false,
    disableVertexColors: true,
    useVariantColor: true,
  },
  "sofa-real-castlery-jaron-3s-wide-arm": {
    brightness: 1.03,
    saturation: 1.05,
    roughnessOverride: 0.44,
    metalnessOverride: 0.04,
    aoMapIntensity: 0.36,
    emissiveBoost: 0,
    specularIntensityOverride: 0.58,
    clearcoatOverride: 0.22,
    clearcoatRoughnessOverride: 0.6,
    disableAoMap: false,
    disableVertexColors: true,
    useVariantColor: true,
  },
  "sofa-real-castlery-jaron-extended-3s": {
    brightness: 1.03,
    saturation: 1.05,
    roughnessOverride: 0.44,
    metalnessOverride: 0.04,
    aoMapIntensity: 0.36,
    emissiveBoost: 0,
    specularIntensityOverride: 0.58,
    clearcoatOverride: 0.22,
    clearcoatRoughnessOverride: 0.6,
    disableAoMap: false,
    disableVertexColors: true,
    useVariantColor: true,
  },
  "sofa-real-castlery-jaron-extended-3s-wide-arm": {
    brightness: 1.03,
    saturation: 1.05,
    roughnessOverride: 0.44,
    metalnessOverride: 0.04,
    aoMapIntensity: 0.36,
    swapWidthDepthAxes: false,
  },
  "sofa-real-castlery-jaron-chaise-sectional": {
    brightness: 1.03,
    saturation: 1.05,
    roughnessOverride: 0.44,
    metalnessOverride: 0.04,
    aoMapIntensity: 0.36,
    emissiveBoost: 0,
    specularIntensityOverride: 0.58,
    clearcoatOverride: 0.22,
    clearcoatRoughnessOverride: 0.6,
    disableAoMap: false,
    disableVertexColors: true,
    useVariantColor: true,
    swapWidthDepthAxes: false,
  },
  "sofa-real-castlery-jaron-chaise-sectional-wide-arm": {
    brightness: 1.03,
    saturation: 1.05,
    roughnessOverride: 0.44,
    metalnessOverride: 0.04,
    aoMapIntensity: 0.36,
    emissiveBoost: 0,
    specularIntensityOverride: 0.58,
    clearcoatOverride: 0.22,
    clearcoatRoughnessOverride: 0.6,
    disableAoMap: false,
    disableVertexColors: true,
    useVariantColor: true,
    swapWidthDepthAxes: false,
  },
  "armchair-real-castlery-jaron-recliner-armchair": {
    brightness: 1.03,
    saturation: 1.05,
    roughnessOverride: 0.44,
    metalnessOverride: 0.04,
    aoMapIntensity: 0.36,
    emissiveBoost: 0,
    specularIntensityOverride: 0.58,
    clearcoatOverride: 0.22,
    clearcoatRoughnessOverride: 0.6,
    disableAoMap: false,
    disableVertexColors: true,
    useVariantColor: true,
    swapWidthDepthAxes: false,
  },
  "armchair-real-castlery-jaron-recliner-armchair-wide-arm": {
    brightness: 1.03,
    saturation: 1.05,
    roughnessOverride: 0.44,
    metalnessOverride: 0.04,
    aoMapIntensity: 0.36,
    emissiveBoost: 0,
    specularIntensityOverride: 0.58,
    clearcoatOverride: 0.22,
    clearcoatRoughnessOverride: 0.6,
    disableAoMap: false,
    disableVertexColors: true,
    useVariantColor: true,
    swapWidthDepthAxes: false,
  },
  "sofa-real-castlery-jaron-l-shaped-sectional": {
    brightness: 1.03,
    saturation: 1.05,
    roughnessOverride: 0.44,
    metalnessOverride: 0.04,
    aoMapIntensity: 0.36,
    emissiveBoost: 0,
    specularIntensityOverride: 0.58,
    clearcoatOverride: 0.22,
    clearcoatRoughnessOverride: 0.6,
    disableAoMap: false,
    disableVertexColors: true,
    useVariantColor: true,
    swapWidthDepthAxes: false,
  },
  "sofa-real-castlery-jaron-l-shaped-sectional-wide-arm": {
    brightness: 1.03,
    saturation: 1.05,
    roughnessOverride: 0.44,
    metalnessOverride: 0.04,
    aoMapIntensity: 0.36,
    emissiveBoost: 0,
    specularIntensityOverride: 0.58,
    clearcoatOverride: 0.22,
    clearcoatRoughnessOverride: 0.6,
    disableAoMap: false,
    disableVertexColors: true,
    useVariantColor: true,
    swapWidthDepthAxes: false,
  },
  "dining-real-castlery-forma-oval-150": {
    brightness: 1.2,
    saturation: 0.84,
    roughnessOverride: 0.9,
    metalnessOverride: 0,
    aoMapIntensity: 0.06,
    emissiveBoost: 0.08,
    specularIntensityOverride: 0.06,
    disableAoMap: false,
    disableVertexColors: true,
    useVariantColor: true,
    swapWidthDepthAxes: false,
  },
  "dining-real-castlery-forma-round-90": {
    brightness: 1.2,
    saturation: 0.84,
    roughnessOverride: 0.9,
    metalnessOverride: 0,
    aoMapIntensity: 0.06,
    emissiveBoost: 0.08,
    specularIntensityOverride: 0.06,
    disableAoMap: false,
    disableVertexColors: true,
    useVariantColor: true,
    swapWidthDepthAxes: false,
  },
  "dining-real-castlery-forma-round-120": {
    brightness: 1.2,
    saturation: 0.84,
    roughnessOverride: 0.9,
    metalnessOverride: 0,
    aoMapIntensity: 0.06,
    emissiveBoost: 0.08,
    specularIntensityOverride: 0.06,
    disableAoMap: false,
    disableVertexColors: true,
    useVariantColor: true,
    swapWidthDepthAxes: false,
  },
  "dining-real-castlery-brighton-oval-180": {
    brightness: 1.18,
    saturation: 0.9,
    roughnessOverride: 0.84,
    metalnessOverride: 0,
    aoMapIntensity: 0.1,
    emissiveBoost: 0.03,
    specularIntensityOverride: 0.1,
    disableAoMap: false,
    disableVertexColors: true,
    useVariantColor: true,
    swapWidthDepthAxes: false,
  },
  "dining-real-castlery-sloane-travertine-180": {
    useVariantColor: false,
    swapWidthDepthAxes: false,
  },
  "dining-real-castlery-sloane-travertine-225": {
    useVariantColor: false,
    swapWidthDepthAxes: true,
  },
  "dining-real-castlery-sloane-dining-table-180": {
    useVariantColor: false,
    swapWidthDepthAxes: false,
  },
  "dining-real-castlery-sloane-dining-table-225": {
    useVariantColor: false,
    swapWidthDepthAxes: false,
  },
  "dining-real-castlery-seb-dining-table-150": {
    useVariantColor: false,
    swapWidthDepthAxes: false,
  },
  "dining-real-castlery-seb-dining-table-180": {
    useVariantColor: false,
    swapWidthDepthAxes: false,
  },
  "coffee-real-castlery-harper-marble-rectangular-120": {
    brightness: 1.03,
    saturation: 0.96,
    roughnessOverride: 0.84,
    metalnessOverride: 0,
    aoMapIntensity: 0.18,
    emissiveBoost: 0.02,
    specularIntensityOverride: 0.16,
    disableAoMap: false,
    disableVertexColors: true,
    useVariantColor: false,
    preserveWoodLegMaterials: true,
    preserveWoodLegDisableBaseColorMap: true,
    woodLegDetectionMode: "harper",
  },
  "coffee-real-castlery-harper-marble-round-915": {
    brightness: 1.03,
    saturation: 0.96,
    roughnessOverride: 0.84,
    metalnessOverride: 0,
    aoMapIntensity: 0.18,
    emissiveBoost: 0.02,
    specularIntensityOverride: 0.16,
    disableAoMap: false,
    disableVertexColors: true,
    useVariantColor: false,
    preserveWoodLegMaterials: true,
    preserveWoodLegDisableBaseColorMap: true,
    woodLegDetectionMode: "harper",
  },
  "coffee-real-castlery-bristol-coffee-table-set-walnut": {
    useVariantColor: false,
    swapWidthDepthAxes: false,
  },
  "coffee-real-castlery-vincent-coffee-table-set-walnut": {
    useVariantColor: false,
    swapWidthDepthAxes: false,
  },
  "accessory-real-castlery-cedric-floor-lamp-with-table": {
    // The source GLB's long footprint axis is X, while the catalog's long
    // 44 cm footprint axis is depth. Swap before fitting dimensions so the
    // spherical shade and circular table keep their authored proportions.
    useVariantColor: false,
    swapWidthDepthAxes: true,
  },
  "dining-real-castlery-kelsey-marble-160": {
    brightness: 1.18,
    saturation: 0.88,
    roughnessOverride: 0.86,
    metalnessOverride: 0,
    aoMapIntensity: 0.1,
    emissiveBoost: 0.03,
    specularIntensityOverride: 0.1,
    disableAoMap: false,
    disableVertexColors: true,
    // Keep tabletop marble texture stable; only leg wood tint should change per variant.
    useVariantColor: false,
    preserveWoodLegMaterials: true,
    preserveWoodLegDisableBaseColorMap: true,
    woodLegDetectionMode: "kelsey",
  },
  "dining-real-castlery-kelsey-marble-180": {
    brightness: 1.18,
    saturation: 0.88,
    roughnessOverride: 0.86,
    metalnessOverride: 0,
    aoMapIntensity: 0.1,
    emissiveBoost: 0.03,
    specularIntensityOverride: 0.1,
    disableAoMap: false,
    disableVertexColors: true,
    useVariantColor: false,
    preserveWoodLegMaterials: true,
    preserveWoodLegDisableBaseColorMap: true,
    woodLegDetectionMode: "kelsey",
  },
  "castlery-sloane-sideboard-150cm": {
    brightness: 1.38,
    saturation: 0.92,
    roughnessOverride: 0.78,
    metalnessOverride: 0,
    aoMapIntensity: 0.06,
    emissiveBoost: 0.08,
    specularIntensityOverride: 0.08,
    disableAoMap: true,
    disableVertexColors: true,
    // Keep native wood texture/lightness; do not multiply by finish swatch tint.
    useVariantColor: false,
  },
  "castlery-sloane-sideboard-180cm": {
    brightness: 1.38,
    saturation: 0.92,
    roughnessOverride: 0.78,
    metalnessOverride: 0,
    aoMapIntensity: 0.06,
    emissiveBoost: 0.08,
    specularIntensityOverride: 0.08,
    disableAoMap: true,
    disableVertexColors: true,
    // Keep native wood texture/lightness; do not multiply by finish swatch tint.
    useVariantColor: false,
  },
  "storage-real-castlery-sawyer-sideboard-180cm": {
    brightness: 1.42,
    saturation: 0.9,
    roughnessOverride: 0.8,
    metalnessOverride: 0,
    aoMapIntensity: 0.05,
    emissiveBoost: 0.1,
    specularIntensityOverride: 0.08,
    disableAoMap: true,
    disableVertexColors: true,
    // Preserve native oak texture/lightness from GLB.
    useVariantColor: false,
  },
  "castlery-sawyer-sideboard-180cm": {
    brightness: 1.42,
    saturation: 0.9,
    roughnessOverride: 0.8,
    metalnessOverride: 0,
    aoMapIntensity: 0.05,
    emissiveBoost: 0.1,
    specularIntensityOverride: 0.08,
    disableAoMap: true,
    disableVertexColors: true,
    useVariantColor: false,
  },
  "sawyer-sideboard-180cm": {
    brightness: 1.42,
    saturation: 0.9,
    roughnessOverride: 0.8,
    metalnessOverride: 0,
    aoMapIntensity: 0.05,
    emissiveBoost: 0.1,
    specularIntensityOverride: 0.08,
    disableAoMap: true,
    disableVertexColors: true,
    useVariantColor: false,
  },
  "coffee-real-castlery-hugg-nesting-square-performance-basalt-closed": {
    brightness: 1,
    saturation: 1,
    roughnessOverride: 0.78,
    metalnessOverride: 0,
    aoMapIntensity: 0.18,
    emissiveBoost: 0,
    specularIntensityOverride: 0.08,
    disableAoMap: false,
    disableVertexColors: false,
    useVariantColor: false,
    preserveWoodLegMaterials: true,
    preserveWoodLegDisableBaseColorMap: false,
  },
  "coffee-real-castlery-hugg-nesting-square-performance-basalt-opened": {
    brightness: 1,
    saturation: 1,
    roughnessOverride: 0.78,
    metalnessOverride: 0,
    aoMapIntensity: 0.18,
    emissiveBoost: 0,
    specularIntensityOverride: 0.08,
    disableAoMap: false,
    disableVertexColors: false,
    useVariantColor: false,
    preserveWoodLegMaterials: true,
    preserveWoodLegDisableBaseColorMap: false,
  },
  "coffee-real-castlery-hugg-nesting-square-performance-dune-closed": {
    brightness: 1,
    saturation: 1,
    roughnessOverride: 0.78,
    metalnessOverride: 0,
    aoMapIntensity: 0.18,
    emissiveBoost: 0,
    specularIntensityOverride: 0.08,
    disableAoMap: false,
    disableVertexColors: false,
    useVariantColor: false,
    preserveWoodLegMaterials: true,
    preserveWoodLegDisableBaseColorMap: false,
  },
  "coffee-real-castlery-hugg-nesting-square-performance-dune-opened": {
    brightness: 1,
    saturation: 1,
    roughnessOverride: 0.78,
    metalnessOverride: 0,
    aoMapIntensity: 0.18,
    emissiveBoost: 0,
    specularIntensityOverride: 0.08,
    disableAoMap: false,
    disableVertexColors: false,
    useVariantColor: false,
    preserveWoodLegMaterials: true,
    preserveWoodLegDisableBaseColorMap: false,
  },
  "coffee-real-castlery-hugg-nesting-rectangular-performance-basalt-closed": {
    brightness: 1,
    saturation: 1,
    roughnessOverride: 0.78,
    metalnessOverride: 0,
    aoMapIntensity: 0.18,
    emissiveBoost: 0,
    specularIntensityOverride: 0.08,
    disableAoMap: false,
    disableVertexColors: false,
    useVariantColor: false,
    preserveWoodLegMaterials: true,
    preserveWoodLegDisableBaseColorMap: false,
  },
  "coffee-real-castlery-hugg-nesting-rectangular-performance-basalt-opened": {
    brightness: 1,
    saturation: 1,
    roughnessOverride: 0.78,
    metalnessOverride: 0,
    aoMapIntensity: 0.18,
    emissiveBoost: 0,
    specularIntensityOverride: 0.08,
    disableAoMap: false,
    disableVertexColors: false,
    useVariantColor: false,
    preserveWoodLegMaterials: true,
    preserveWoodLegDisableBaseColorMap: false,
  },
  "coffee-real-castlery-hugg-nesting-rectangular-performance-dune-closed": {
    brightness: 1,
    saturation: 1,
    roughnessOverride: 0.78,
    metalnessOverride: 0,
    aoMapIntensity: 0.18,
    emissiveBoost: 0,
    specularIntensityOverride: 0.08,
    disableAoMap: false,
    disableVertexColors: false,
    useVariantColor: false,
    preserveWoodLegMaterials: true,
    preserveWoodLegDisableBaseColorMap: false,
  },
  "coffee-real-castlery-hugg-nesting-rectangular-performance-dune-opened": {
    brightness: 1,
    saturation: 1,
    roughnessOverride: 0.78,
    metalnessOverride: 0,
    aoMapIntensity: 0.18,
    emissiveBoost: 0,
    specularIntensityOverride: 0.08,
    disableAoMap: false,
    disableVertexColors: false,
    useVariantColor: false,
    preserveWoodLegMaterials: true,
    preserveWoodLegDisableBaseColorMap: false,
  },
  "coffee-real-castlery-hugg-nesting-side-table-performance-basalt-closed": {
    brightness: 1,
    saturation: 1,
    roughnessOverride: 0.78,
    metalnessOverride: 0,
    aoMapIntensity: 0.18,
    emissiveBoost: 0,
    specularIntensityOverride: 0.08,
    disableAoMap: false,
    disableVertexColors: false,
    useVariantColor: false,
    preserveWoodLegMaterials: true,
    preserveWoodLegDisableBaseColorMap: false,
  },
  "coffee-real-castlery-hugg-nesting-side-table-performance-basalt-opened": {
    brightness: 1,
    saturation: 1,
    roughnessOverride: 0.78,
    metalnessOverride: 0,
    aoMapIntensity: 0.18,
    emissiveBoost: 0,
    specularIntensityOverride: 0.08,
    disableAoMap: false,
    disableVertexColors: false,
    useVariantColor: false,
    preserveWoodLegMaterials: true,
    preserveWoodLegDisableBaseColorMap: false,
  },
  "coffee-real-castlery-hugg-nesting-side-table-performance-dune-closed": {
    brightness: 1,
    saturation: 1,
    roughnessOverride: 0.78,
    metalnessOverride: 0,
    aoMapIntensity: 0.18,
    emissiveBoost: 0,
    specularIntensityOverride: 0.08,
    disableAoMap: false,
    disableVertexColors: false,
    useVariantColor: false,
    preserveWoodLegMaterials: true,
    preserveWoodLegDisableBaseColorMap: false,
  },
  "coffee-real-castlery-hugg-nesting-side-table-performance-dune-opened": {
    brightness: 1,
    saturation: 1,
    roughnessOverride: 0.78,
    metalnessOverride: 0,
    aoMapIntensity: 0.18,
    emissiveBoost: 0,
    specularIntensityOverride: 0.08,
    disableAoMap: false,
    disableVertexColors: false,
    useVariantColor: false,
    preserveWoodLegMaterials: true,
    preserveWoodLegDisableBaseColorMap: false,
  },
};

export function getModelCalibration(product: { id: string }): GLBCalibration | undefined {
  const explicitCalibration = GLB_CALIBRATION_BY_PRODUCT_ID[product.id];
  if (explicitCalibration) return explicitCalibration;

  if (product.id.startsWith("sofa-real-castlery-")) {
    return STANDARD_IMPORTED_CASTLERY_SOFA_CALIBRATION;
  }

  return undefined;
}
