import type { FloorPlanDocumentV2 } from "@/lib/floor-plan-document-v2";
import type {
  FloorPlanAddressTransform,
  FloorPlanVerificationTier,
} from "@/lib/floor-plan-imports/types";
import {
  resolveFloorPlanAuthoredConfiguration,
  validateFloorPlanConfigurationGroup,
  type FloorPlanAuthoredConfigurationGroup,
} from "@/lib/floor-plan-optional-configurations";

const SAFE_ID = /^[a-z0-9][a-z0-9:_-]{0,199}$/i;
const SHA256 = /^[a-f0-9]{64}$/;
const PUBLIC_TIERS = new Set(["source_verified", "construction_verified"]);

export type FloorPlanAuthoredVariantApprovalRequest = {
  groupId: string;
  label: string;
  variants: Array<{
    optionId: string;
    label: string;
    revisionId: string;
    addressBindingId: string;
    geometryHash: string;
    sourceId: string;
    pageNumber?: number;
    defaultSelected: boolean;
  }>;
};

export type FloorPlanAuthoredVariantRevisionSnapshot = {
  id: string;
  geometryHash: string;
  verificationTier: string;
  publicationStatus: string;
  publishedAt: Date | string | null;
  document: FloorPlanDocumentV2;
  servingIntegrityValid: boolean;
  addressBinding: {
    id: string;
    revisionId: string;
    countryCode: string;
    addressNormalized: string;
    block: string;
    street: string;
    postalCode: string | null;
    stack: string | null;
    floorMin: number | null;
    floorMax: number | null;
    transform: FloorPlanAddressTransform;
    role: "catalog" | "authored_variant";
  };
};

export type PublicFloorPlanAuthoredVariantGroup = {
  groupId: string;
  label: string;
  defaultOptionId: string;
  options: Array<{
    optionId: string;
    label: string;
    revisionId: string;
    revisionUrl: string;
    geometryHash: string;
    verificationTier: FloorPlanVerificationTier;
    defaultSelected: boolean;
    sourcePage: number | null;
    addressBinding: {
      id: string;
      transform: FloorPlanAddressTransform;
    };
  }>;
};

export type PersistedFloorPlanAuthoredVariantGroup = {
  groupKey: string;
  label: string;
  publicationStatus: string;
  approvedByEmail: string | null;
  publishedAt: Date | string | null;
  publishedByEmail: string | null;
  options: Array<{
    optionKey: string;
    label: string;
    revisionId: string;
    addressBindingId: string;
    geometryHash: string;
    sourceId: string;
    sourcePage: number | null;
    defaultSelected: boolean;
    sourceEvidenceJson: unknown;
    revision: {
      id: string;
      geometryHash: string;
      verificationTier: string;
      publicationStatus: string;
      publishedAt: Date | string | null;
    };
    addressBinding: {
      id: string;
      revisionId: string;
      transform: FloorPlanAddressTransform;
      role: "catalog" | "authored_variant";
    };
  }>;
};

function fail(message: string): never {
  throw new Error(`Invalid floor-plan authored variant link: ${message}`);
}

function isRecord(value: unknown): value is Record<string, unknown> {
  return Boolean(value) && typeof value === "object" && !Array.isArray(value);
}

function requiredText(value: unknown, field: string, maximum = 200): string {
  if (typeof value !== "string") fail(`${field} is required`);
  const text = value.trim();
  if (!text || text.length > maximum) fail(`${field} is invalid`);
  return text;
}

function stableId(value: unknown, field: string): string {
  const id = requiredText(value, field);
  if (!SAFE_ID.test(id)) fail(`${field} must be a stable identifier`);
  return id;
}

function bindingIdentity(binding: FloorPlanAuthoredVariantRevisionSnapshot["addressBinding"]) {
  return JSON.stringify([
    binding.countryCode.toUpperCase(),
    binding.addressNormalized.trim().toLowerCase(),
    binding.block.trim().toLowerCase(),
    binding.street.trim().toLowerCase(),
    binding.postalCode?.trim().toLowerCase() ?? null,
    binding.stack?.trim().toUpperCase() ?? null,
    binding.floorMin,
    binding.floorMax,
  ]);
}

/**
 * Parses the small admin contract. Source evidence JSON is generated by the
 * server from these allowlisted fields; arbitrary manifests are never copied.
 */
export function parseFloorPlanAuthoredVariantApprovalRequest(
  value: Record<string, unknown>
): FloorPlanAuthoredVariantApprovalRequest {
  const rawVariants = value.variants;
  if (!Array.isArray(rawVariants) || rawVariants.length < 2 || rawVariants.length > 20) {
    fail("variants must contain between 2 and 20 options");
  }
  return {
    groupId: stableId(value.groupId, "groupId"),
    label: requiredText(value.label, "label"),
    variants: rawVariants.map((raw, index) => {
      if (!raw || typeof raw !== "object" || Array.isArray(raw)) {
        fail(`variants[${index}] is invalid`);
      }
      const variant = raw as Record<string, unknown>;
      const pageNumber = variant.pageNumber;
      if (
        pageNumber !== undefined &&
        (!Number.isSafeInteger(pageNumber) || Number(pageNumber) < 1)
      ) {
        fail(`variants[${index}].pageNumber is invalid`);
      }
      const geometryHash = requiredText(
        variant.geometryHash,
        `variants[${index}].geometryHash`,
        64
      ).toLowerCase();
      if (!SHA256.test(geometryHash)) fail(`variants[${index}].geometryHash is invalid`);
      if (typeof variant.defaultSelected !== "boolean") {
        fail(`variants[${index}].defaultSelected is required`);
      }
      return {
        optionId: stableId(variant.optionId, `variants[${index}].optionId`),
        label: requiredText(variant.label, `variants[${index}].label`),
        revisionId: stableId(variant.revisionId, `variants[${index}].revisionId`),
        addressBindingId: stableId(
          variant.addressBindingId,
          `variants[${index}].addressBindingId`
        ),
        geometryHash,
        sourceId: stableId(variant.sourceId, `variants[${index}].sourceId`),
        ...(pageNumber === undefined ? {} : { pageNumber: Number(pageNumber) }),
        defaultSelected: variant.defaultSelected,
      };
    }),
  };
}

/** Fail-closed approval/publish validation over immutable revision snapshots. */
export function validateFloorPlanAuthoredVariantApproval(input: {
  request: FloorPlanAuthoredVariantApprovalRequest;
  revisions: FloorPlanAuthoredVariantRevisionSnapshot[];
}): FloorPlanAuthoredConfigurationGroup {
  const snapshots = new Map(input.revisions.map((revision) => [revision.id, revision]));
  if (snapshots.size !== input.revisions.length) fail("duplicate revision snapshot");
  const group: FloorPlanAuthoredConfigurationGroup = {
    groupId: input.request.groupId,
    label: input.request.label,
    sourceSupported: true,
    variants: input.request.variants.map((variant) => ({
      optionId: variant.optionId,
      label: variant.label,
      defaultSelected: variant.defaultSelected,
      sourceSupported: true,
      artifact: {
        kind: "authored_revision",
        revisionId: variant.revisionId,
        geometryHash: variant.geometryHash,
        sourceId: variant.sourceId,
        ...(variant.pageNumber === undefined ? {} : { pageNumber: variant.pageNumber }),
      },
    })),
  };
  validateFloorPlanConfigurationGroup(group);

  let expectedBindingIdentity: string | null = null;
  for (const variant of input.request.variants) {
    const snapshot = snapshots.get(variant.revisionId);
    if (!snapshot) fail(`revision ${variant.revisionId} was not loaded`);
    if (
      snapshot.publicationStatus !== "published" ||
      !snapshot.publishedAt ||
      !PUBLIC_TIERS.has(snapshot.verificationTier) ||
      !snapshot.servingIntegrityValid
    ) {
      fail(`revision ${variant.revisionId} is not a serving-integrity-valid publication`);
    }
    if (snapshot.geometryHash !== variant.geometryHash) {
      fail(`revision ${variant.revisionId} geometry hash changed`);
    }
    if (
      snapshot.addressBinding.id !== variant.addressBindingId ||
      snapshot.addressBinding.revisionId !== snapshot.id
    ) {
      fail(`revision ${variant.revisionId} address binding does not match`);
    }
    const expectedRole = variant.defaultSelected ? "catalog" : "authored_variant";
    if (snapshot.addressBinding.role !== expectedRole) {
      fail(
        variant.defaultSelected
          ? "the default option must use a searchable catalog binding"
          : "alternate options must use non-searchable authored-variant bindings"
      );
    }
    const identity = bindingIdentity(snapshot.addressBinding);
    expectedBindingIdentity ??= identity;
    if (identity !== expectedBindingIdentity) {
      fail("all options must describe the same address, stack and floor range");
    }
    resolveFloorPlanAuthoredConfiguration({
      group,
      optionId: variant.optionId,
      document: snapshot.document,
    });
  }
  return structuredClone(group);
}

/** Strict public projection; malformed, stale or retired groups disappear. */
export function projectPublicFloorPlanAuthoredVariantGroups(
  groups: PersistedFloorPlanAuthoredVariantGroup[],
  currentRevisionId: string,
  currentAddressBindingId?: string
): PublicFloorPlanAuthoredVariantGroup[] {
  const projected: PublicFloorPlanAuthoredVariantGroup[] = [];
  const seen = new Set<string>();
  for (const group of groups) {
    if (seen.has(group.groupKey)) continue;
    seen.add(group.groupKey);
    const reviewer = group.approvedByEmail?.trim().toLowerCase() ?? "";
    const publisher = group.publishedByEmail?.trim().toLowerCase() ?? "";
    if (
      group.publicationStatus !== "published" ||
      !group.publishedAt ||
      !reviewer ||
      !publisher ||
      reviewer === publisher ||
      !SAFE_ID.test(group.groupKey) ||
      !group.label.trim() ||
      group.options.length < 2 ||
      !group.options.some(
        (option) =>
          option.revisionId === currentRevisionId &&
          (!currentAddressBindingId || option.addressBindingId === currentAddressBindingId)
      ) ||
      group.options.filter((option) => option.defaultSelected).length !== 1
    ) {
      continue;
    }
    const optionKeys = new Set<string>();
    const revisionIds = new Set<string>();
    const options = group.options.flatMap((option) => {
      const evidence = isRecord(option.sourceEvidenceJson)
        ? option.sourceEvidenceJson
        : null;
      if (
        optionKeys.has(option.optionKey) ||
        revisionIds.has(option.revisionId) ||
        !SAFE_ID.test(option.optionKey) ||
        !option.label.trim() ||
        !SHA256.test(option.geometryHash) ||
        option.revision.id !== option.revisionId ||
        option.revision.geometryHash !== option.geometryHash ||
        option.revision.publicationStatus !== "published" ||
        !option.revision.publishedAt ||
        !PUBLIC_TIERS.has(option.revision.verificationTier) ||
        option.addressBinding.id !== option.addressBindingId ||
        option.addressBinding.revisionId !== option.revisionId ||
        (option.defaultSelected
          ? option.addressBinding.role !== "catalog"
          : option.addressBinding.role !== "authored_variant") ||
        !SAFE_ID.test(option.sourceId) ||
        (option.sourcePage !== null && option.sourcePage < 1) ||
        !evidence ||
        evidence.basis !== "direct_source_configuration" ||
        evidence.sourceId !== option.sourceId ||
        evidence.pageNumber !== option.sourcePage ||
        evidence.revisionId !== option.revisionId ||
        evidence.geometryHash !== option.geometryHash
      ) {
        return [];
      }
      optionKeys.add(option.optionKey);
      revisionIds.add(option.revisionId);
      return [{
        optionId: option.optionKey,
        label: option.label.trim(),
        revisionId: option.revisionId,
        revisionUrl: `/api/floor-plans/revisions/${encodeURIComponent(option.revisionId)}`,
        geometryHash: option.geometryHash,
        verificationTier: option.revision.verificationTier as FloorPlanVerificationTier,
        defaultSelected: option.defaultSelected,
        sourcePage: option.sourcePage,
        addressBinding: {
          id: option.addressBinding.id,
          transform: option.addressBinding.transform,
        },
      }];
    });
    if (options.length !== group.options.length) continue;
    projected.push({
      groupId: group.groupKey,
      label: group.label.trim(),
      defaultOptionId: options.find((option) => option.defaultSelected)!.optionId,
      options,
    });
  }
  return projected;
}
