import fs from "node:fs";
import path from "node:path";
import { parse } from "yaml";
import type { SurfaceMaterial } from "../lib/surface-material-schema";
import type { SurfaceMaterialRenderInfo } from "../lib/surface-material-runtime";

const GENERATED_PATH = path.join(
  process.cwd(),
  "lib",
  "generated",
  "surface-material-runtime.generated.ts"
);
const PRODUCTION_ROOT = path.join(process.cwd(), "catalog", "surface-materials");
const TEST_FIXTURE_ROOT = path.join(process.cwd(), "tests", "fixtures", "surface-materials");
const CHECK_MODE = process.argv.includes("--check");

type SurfaceMaterialYamlEntry = SurfaceMaterial & {
  file_path: string;
};

function findCatalogFiles(rootDir: string): string[] {
  if (!fs.existsSync(rootDir)) return [];

  const files: string[] = [];
  for (const entry of fs.readdirSync(rootDir, { withFileTypes: true })) {
    const fullPath = path.join(rootDir, entry.name);
    if (entry.isDirectory()) {
      files.push(...findCatalogFiles(fullPath));
      continue;
    }
    if (entry.name === "catalog.yaml") files.push(fullPath);
  }

  return files.sort((a, b) => a.localeCompare(b));
}

function readSurfaceMaterial(filePath: string): SurfaceMaterialYamlEntry {
  return {
    ...(parse(fs.readFileSync(filePath, "utf8")) as SurfaceMaterial),
    file_path: filePath,
  };
}

function sortMaterials(entries: SurfaceMaterialYamlEntry[]): SurfaceMaterialYamlEntry[] {
  return [...entries].sort((a, b) => {
    const aId = a.surface_material?.material_id ?? "";
    const bId = b.surface_material?.material_id ?? "";
    return aId.localeCompare(bId);
  });
}

function toRenderInfo(entry: SurfaceMaterialYamlEntry): SurfaceMaterialRenderInfo {
  return {
    surface_material: {
      supplier: entry.surface_material.supplier,
      brand: entry.surface_material.brand ?? null,
      material_id: entry.surface_material.material_id,
      slug: entry.surface_material.slug,
      product_name: entry.surface_material.product_name,
      surface_category: entry.surface_material.surface_category,
      material_family: entry.surface_material.material_family,
    },
    source: {
      source_url: entry.source.source_url,
      sample_request_url: entry.source.sample_request_url ?? null,
      license_status: entry.source.license_status,
    },
    classification: {
      design_effect: entry.classification.design_effect,
      color_family: entry.classification.color_family,
      tone: entry.classification.tone,
      style_cluster: entry.classification.style_cluster,
      room_suitability: entry.classification.room_suitability,
    },
    physical_specs: {
      plank_width_mm: entry.physical_specs.plank_width_mm ?? null,
      plank_length_mm: entry.physical_specs.plank_length_mm ?? null,
      tile_width_mm: entry.physical_specs.tile_width_mm ?? null,
      tile_length_mm: entry.physical_specs.tile_length_mm ?? null,
      total_thickness_mm: entry.physical_specs.total_thickness_mm ?? null,
      wear_layer_mm: entry.physical_specs.wear_layer_mm ?? null,
      waterproof: entry.physical_specs.waterproof ?? null,
      suitable_for_outdoor: entry.physical_specs.suitable_for_outdoor ?? null,
      commercial_grade: entry.physical_specs.commercial_grade ?? null,
    },
    texture_assets: {
      swatch_url: entry.texture_assets.swatch_url ?? null,
      base_color_url: entry.texture_assets.base_color_url ?? null,
      normal_url: entry.texture_assets.normal_url ?? null,
      roughness_url: entry.texture_assets.roughness_url ?? null,
      ao_url: entry.texture_assets.ao_url ?? null,
      preview_room_url: entry.texture_assets.preview_room_url ?? null,
      tileable: entry.texture_assets.tileable,
      texture_repeat_size_cm: entry.texture_assets.texture_repeat_size_cm ?? null,
    },
    rendering: entry.rendering,
    commerce: {
      purchase_mode: entry.commerce.purchase_mode,
      sample_available: entry.commerce.sample_available,
      sample_request_url: entry.commerce.sample_request_url ?? null,
    },
    import_governance: {
      publish_status: entry.import_governance.publish_status,
      publish_blockers: entry.import_governance.publish_blockers,
    },
  };
}

function stableStringify(value: unknown): string {
  return JSON.stringify(value, null, 2);
}

function renderArray(name: string, entries: SurfaceMaterialYamlEntry[]): string {
  const renderInfos = sortMaterials(entries).map(toRenderInfo);
  return `export const ${name}: SurfaceMaterialRenderInfo[] = ${stableStringify(renderInfos)};\n`;
}

function buildGeneratedFile(): string {
  const productionEntries = findCatalogFiles(PRODUCTION_ROOT).map(readSurfaceMaterial);
  const testFixtureEntries = findCatalogFiles(TEST_FIXTURE_ROOT).map(readSurfaceMaterial);

  return `${[
    "// This file is generated by scripts/generate-surface-material-runtime.ts.",
    "// Do not edit manually. Update catalog/surface-materials YAML and rerun generation.",
    "",
    'import type { SurfaceMaterialRenderInfo } from "../surface-material-runtime";',
    "",
    renderArray("PRODUCTION_SURFACE_MATERIAL_RENDER_REGISTRY", productionEntries),
    renderArray("TEST_FIXTURE_SURFACE_MATERIAL_RENDER_REGISTRY", testFixtureEntries),
  ].join("\n").trimEnd()}\n`;
}

const nextContents = buildGeneratedFile();
const currentContents = fs.existsSync(GENERATED_PATH)
  ? fs.readFileSync(GENERATED_PATH, "utf8")
  : "";

if (CHECK_MODE) {
  if (currentContents !== nextContents) {
    console.error("Surface material runtime data is stale. Run npm run generate:surface-material-runtime.");
    process.exit(1);
  }
  console.log("Surface material runtime data is up to date.");
} else {
  fs.writeFileSync(GENERATED_PATH, nextContents);
  console.log(`Generated ${path.relative(process.cwd(), GENERATED_PATH)}.`);
}
